/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ResourceGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceGroup{}

// ResourceGroup struct for ResourceGroup
type ResourceGroup struct {
	GroupId int32 `json:"group_id"`
	GroupName string `json:"group_name"`
	GroupParentId *int64 `json:"group_parent_id,omitempty"`
	GroupSort *int32 `json:"group_sort,omitempty"`
	GroupLevel *int32 `json:"group_level,omitempty"`
	DingWebhook *string `json:"ding_webhook,omitempty"`
	FeishuWebhook *string `json:"feishu_webhook,omitempty"`
	QywxWebhook *string `json:"qywx_webhook,omitempty"`
	IsDeleted *IsOfflineExportEnum `json:"is_deleted,omitempty"`
	CreateTime time.Time `json:"create_time"`
	SysTime time.Time `json:"sys_time"`
}

type _ResourceGroup ResourceGroup

// NewResourceGroup instantiates a new ResourceGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceGroup(groupId int32, groupName string, createTime time.Time, sysTime time.Time) *ResourceGroup {
	this := ResourceGroup{}
	this.GroupId = groupId
	this.GroupName = groupName
	this.CreateTime = createTime
	this.SysTime = sysTime
	return &this
}

// NewResourceGroupWithDefaults instantiates a new ResourceGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceGroupWithDefaults() *ResourceGroup {
	this := ResourceGroup{}
	return &this
}

// GetGroupId returns the GroupId field value
func (o *ResourceGroup) GetGroupId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *ResourceGroup) GetGroupIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *ResourceGroup) SetGroupId(v int32) {
	o.GroupId = v
}

// GetGroupName returns the GroupName field value
func (o *ResourceGroup) GetGroupName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value
// and a boolean to check if the value has been set.
func (o *ResourceGroup) GetGroupNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupName, true
}

// SetGroupName sets field value
func (o *ResourceGroup) SetGroupName(v string) {
	o.GroupName = v
}

// GetGroupParentId returns the GroupParentId field value if set, zero value otherwise.
func (o *ResourceGroup) GetGroupParentId() int64 {
	if o == nil || IsNil(o.GroupParentId) {
		var ret int64
		return ret
	}
	return *o.GroupParentId
}

// GetGroupParentIdOk returns a tuple with the GroupParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceGroup) GetGroupParentIdOk() (*int64, bool) {
	if o == nil || IsNil(o.GroupParentId) {
		return nil, false
	}
	return o.GroupParentId, true
}

// HasGroupParentId returns a boolean if a field has been set.
func (o *ResourceGroup) HasGroupParentId() bool {
	if o != nil && !IsNil(o.GroupParentId) {
		return true
	}

	return false
}

// SetGroupParentId gets a reference to the given int64 and assigns it to the GroupParentId field.
func (o *ResourceGroup) SetGroupParentId(v int64) {
	o.GroupParentId = &v
}

// GetGroupSort returns the GroupSort field value if set, zero value otherwise.
func (o *ResourceGroup) GetGroupSort() int32 {
	if o == nil || IsNil(o.GroupSort) {
		var ret int32
		return ret
	}
	return *o.GroupSort
}

// GetGroupSortOk returns a tuple with the GroupSort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceGroup) GetGroupSortOk() (*int32, bool) {
	if o == nil || IsNil(o.GroupSort) {
		return nil, false
	}
	return o.GroupSort, true
}

// HasGroupSort returns a boolean if a field has been set.
func (o *ResourceGroup) HasGroupSort() bool {
	if o != nil && !IsNil(o.GroupSort) {
		return true
	}

	return false
}

// SetGroupSort gets a reference to the given int32 and assigns it to the GroupSort field.
func (o *ResourceGroup) SetGroupSort(v int32) {
	o.GroupSort = &v
}

// GetGroupLevel returns the GroupLevel field value if set, zero value otherwise.
func (o *ResourceGroup) GetGroupLevel() int32 {
	if o == nil || IsNil(o.GroupLevel) {
		var ret int32
		return ret
	}
	return *o.GroupLevel
}

// GetGroupLevelOk returns a tuple with the GroupLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceGroup) GetGroupLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.GroupLevel) {
		return nil, false
	}
	return o.GroupLevel, true
}

// HasGroupLevel returns a boolean if a field has been set.
func (o *ResourceGroup) HasGroupLevel() bool {
	if o != nil && !IsNil(o.GroupLevel) {
		return true
	}

	return false
}

// SetGroupLevel gets a reference to the given int32 and assigns it to the GroupLevel field.
func (o *ResourceGroup) SetGroupLevel(v int32) {
	o.GroupLevel = &v
}

// GetDingWebhook returns the DingWebhook field value if set, zero value otherwise.
func (o *ResourceGroup) GetDingWebhook() string {
	if o == nil || IsNil(o.DingWebhook) {
		var ret string
		return ret
	}
	return *o.DingWebhook
}

// GetDingWebhookOk returns a tuple with the DingWebhook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceGroup) GetDingWebhookOk() (*string, bool) {
	if o == nil || IsNil(o.DingWebhook) {
		return nil, false
	}
	return o.DingWebhook, true
}

// HasDingWebhook returns a boolean if a field has been set.
func (o *ResourceGroup) HasDingWebhook() bool {
	if o != nil && !IsNil(o.DingWebhook) {
		return true
	}

	return false
}

// SetDingWebhook gets a reference to the given string and assigns it to the DingWebhook field.
func (o *ResourceGroup) SetDingWebhook(v string) {
	o.DingWebhook = &v
}

// GetFeishuWebhook returns the FeishuWebhook field value if set, zero value otherwise.
func (o *ResourceGroup) GetFeishuWebhook() string {
	if o == nil || IsNil(o.FeishuWebhook) {
		var ret string
		return ret
	}
	return *o.FeishuWebhook
}

// GetFeishuWebhookOk returns a tuple with the FeishuWebhook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceGroup) GetFeishuWebhookOk() (*string, bool) {
	if o == nil || IsNil(o.FeishuWebhook) {
		return nil, false
	}
	return o.FeishuWebhook, true
}

// HasFeishuWebhook returns a boolean if a field has been set.
func (o *ResourceGroup) HasFeishuWebhook() bool {
	if o != nil && !IsNil(o.FeishuWebhook) {
		return true
	}

	return false
}

// SetFeishuWebhook gets a reference to the given string and assigns it to the FeishuWebhook field.
func (o *ResourceGroup) SetFeishuWebhook(v string) {
	o.FeishuWebhook = &v
}

// GetQywxWebhook returns the QywxWebhook field value if set, zero value otherwise.
func (o *ResourceGroup) GetQywxWebhook() string {
	if o == nil || IsNil(o.QywxWebhook) {
		var ret string
		return ret
	}
	return *o.QywxWebhook
}

// GetQywxWebhookOk returns a tuple with the QywxWebhook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceGroup) GetQywxWebhookOk() (*string, bool) {
	if o == nil || IsNil(o.QywxWebhook) {
		return nil, false
	}
	return o.QywxWebhook, true
}

// HasQywxWebhook returns a boolean if a field has been set.
func (o *ResourceGroup) HasQywxWebhook() bool {
	if o != nil && !IsNil(o.QywxWebhook) {
		return true
	}

	return false
}

// SetQywxWebhook gets a reference to the given string and assigns it to the QywxWebhook field.
func (o *ResourceGroup) SetQywxWebhook(v string) {
	o.QywxWebhook = &v
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *ResourceGroup) GetIsDeleted() IsOfflineExportEnum {
	if o == nil || IsNil(o.IsDeleted) {
		var ret IsOfflineExportEnum
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceGroup) GetIsDeletedOk() (*IsOfflineExportEnum, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *ResourceGroup) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given IsOfflineExportEnum and assigns it to the IsDeleted field.
func (o *ResourceGroup) SetIsDeleted(v IsOfflineExportEnum) {
	o.IsDeleted = &v
}

// GetCreateTime returns the CreateTime field value
func (o *ResourceGroup) GetCreateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value
// and a boolean to check if the value has been set.
func (o *ResourceGroup) GetCreateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreateTime, true
}

// SetCreateTime sets field value
func (o *ResourceGroup) SetCreateTime(v time.Time) {
	o.CreateTime = v
}

// GetSysTime returns the SysTime field value
func (o *ResourceGroup) GetSysTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.SysTime
}

// GetSysTimeOk returns a tuple with the SysTime field value
// and a boolean to check if the value has been set.
func (o *ResourceGroup) GetSysTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SysTime, true
}

// SetSysTime sets field value
func (o *ResourceGroup) SetSysTime(v time.Time) {
	o.SysTime = v
}

func (o ResourceGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["group_id"] = o.GroupId
	toSerialize["group_name"] = o.GroupName
	if !IsNil(o.GroupParentId) {
		toSerialize["group_parent_id"] = o.GroupParentId
	}
	if !IsNil(o.GroupSort) {
		toSerialize["group_sort"] = o.GroupSort
	}
	if !IsNil(o.GroupLevel) {
		toSerialize["group_level"] = o.GroupLevel
	}
	if !IsNil(o.DingWebhook) {
		toSerialize["ding_webhook"] = o.DingWebhook
	}
	if !IsNil(o.FeishuWebhook) {
		toSerialize["feishu_webhook"] = o.FeishuWebhook
	}
	if !IsNil(o.QywxWebhook) {
		toSerialize["qywx_webhook"] = o.QywxWebhook
	}
	if !IsNil(o.IsDeleted) {
		toSerialize["is_deleted"] = o.IsDeleted
	}
	toSerialize["create_time"] = o.CreateTime
	toSerialize["sys_time"] = o.SysTime
	return toSerialize, nil
}

func (o *ResourceGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"group_id",
		"group_name",
		"create_time",
		"sys_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceGroup := _ResourceGroup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResourceGroup)

	if err != nil {
		return err
	}

	*o = ResourceGroup(varResourceGroup)

	return err
}

type NullableResourceGroup struct {
	value *ResourceGroup
	isSet bool
}

func (v NullableResourceGroup) Get() *ResourceGroup {
	return v.value
}

func (v *NullableResourceGroup) Set(val *ResourceGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceGroup(val *ResourceGroup) *NullableResourceGroup {
	return &NullableResourceGroup{value: val, isSet: true}
}

func (v NullableResourceGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


