/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CloudAccessKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudAccessKey{}

// CloudAccessKey struct for CloudAccessKey
type CloudAccessKey struct {
	Id int32 `json:"id"`
	Type *CloudAccessKeyTypeEnum `json:"type,omitempty"`
	KeyId string `json:"key_id"`
	KeySecret string `json:"key_secret"`
	Remark *string `json:"remark,omitempty"`
}

type _CloudAccessKey CloudAccessKey

// NewCloudAccessKey instantiates a new CloudAccessKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudAccessKey(id int32, keyId string, keySecret string) *CloudAccessKey {
	this := CloudAccessKey{}
	this.Id = id
	this.KeyId = keyId
	this.KeySecret = keySecret
	return &this
}

// NewCloudAccessKeyWithDefaults instantiates a new CloudAccessKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudAccessKeyWithDefaults() *CloudAccessKey {
	this := CloudAccessKey{}
	return &this
}

// GetId returns the Id field value
func (o *CloudAccessKey) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CloudAccessKey) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CloudAccessKey) SetId(v int32) {
	o.Id = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CloudAccessKey) GetType() CloudAccessKeyTypeEnum {
	if o == nil || IsNil(o.Type) {
		var ret CloudAccessKeyTypeEnum
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudAccessKey) GetTypeOk() (*CloudAccessKeyTypeEnum, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CloudAccessKey) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given CloudAccessKeyTypeEnum and assigns it to the Type field.
func (o *CloudAccessKey) SetType(v CloudAccessKeyTypeEnum) {
	o.Type = &v
}

// GetKeyId returns the KeyId field value
func (o *CloudAccessKey) GetKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value
// and a boolean to check if the value has been set.
func (o *CloudAccessKey) GetKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyId, true
}

// SetKeyId sets field value
func (o *CloudAccessKey) SetKeyId(v string) {
	o.KeyId = v
}

// GetKeySecret returns the KeySecret field value
func (o *CloudAccessKey) GetKeySecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeySecret
}

// GetKeySecretOk returns a tuple with the KeySecret field value
// and a boolean to check if the value has been set.
func (o *CloudAccessKey) GetKeySecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeySecret, true
}

// SetKeySecret sets field value
func (o *CloudAccessKey) SetKeySecret(v string) {
	o.KeySecret = v
}

// GetRemark returns the Remark field value if set, zero value otherwise.
func (o *CloudAccessKey) GetRemark() string {
	if o == nil || IsNil(o.Remark) {
		var ret string
		return ret
	}
	return *o.Remark
}

// GetRemarkOk returns a tuple with the Remark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudAccessKey) GetRemarkOk() (*string, bool) {
	if o == nil || IsNil(o.Remark) {
		return nil, false
	}
	return o.Remark, true
}

// HasRemark returns a boolean if a field has been set.
func (o *CloudAccessKey) HasRemark() bool {
	if o != nil && !IsNil(o.Remark) {
		return true
	}

	return false
}

// SetRemark gets a reference to the given string and assigns it to the Remark field.
func (o *CloudAccessKey) SetRemark(v string) {
	o.Remark = &v
}

func (o CloudAccessKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudAccessKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["key_id"] = o.KeyId
	toSerialize["key_secret"] = o.KeySecret
	if !IsNil(o.Remark) {
		toSerialize["remark"] = o.Remark
	}
	return toSerialize, nil
}

func (o *CloudAccessKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"key_id",
		"key_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCloudAccessKey := _CloudAccessKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCloudAccessKey)

	if err != nil {
		return err
	}

	*o = CloudAccessKey(varCloudAccessKey)

	return err
}

type NullableCloudAccessKey struct {
	value *CloudAccessKey
	isSet bool
}

func (v NullableCloudAccessKey) Get() *CloudAccessKey {
	return v.value
}

func (v *NullableCloudAccessKey) Set(val *CloudAccessKey) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudAccessKey) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudAccessKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudAccessKey(val *CloudAccessKey) *NullableCloudAccessKey {
	return &NullableCloudAccessKey{value: val, isSet: true}
}

func (v NullableCloudAccessKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudAccessKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


