/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstanceResourceList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceResourceList{}

// InstanceResourceList struct for InstanceResourceList
type InstanceResourceList struct {
	Count int32 `json:"count"`
	Result []interface{} `json:"result"`
}

type _InstanceResourceList InstanceResourceList

// NewInstanceResourceList instantiates a new InstanceResourceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceResourceList(count int32, result []interface{}) *InstanceResourceList {
	this := InstanceResourceList{}
	this.Count = count
	this.Result = result
	return &this
}

// NewInstanceResourceListWithDefaults instantiates a new InstanceResourceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceResourceListWithDefaults() *InstanceResourceList {
	this := InstanceResourceList{}
	return &this
}

// GetCount returns the Count field value
func (o *InstanceResourceList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *InstanceResourceList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *InstanceResourceList) SetCount(v int32) {
	o.Count = v
}

// GetResult returns the Result field value
func (o *InstanceResourceList) GetResult() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *InstanceResourceList) GetResultOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *InstanceResourceList) SetResult(v []interface{}) {
	o.Result = v
}

func (o InstanceResourceList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceResourceList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *InstanceResourceList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceResourceList := _InstanceResourceList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceResourceList)

	if err != nil {
		return err
	}

	*o = InstanceResourceList(varInstanceResourceList)

	return err
}

type NullableInstanceResourceList struct {
	value *InstanceResourceList
	isSet bool
}

func (v NullableInstanceResourceList) Get() *InstanceResourceList {
	return v.value
}

func (v *NullableInstanceResourceList) Set(val *InstanceResourceList) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceResourceList) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceResourceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceResourceList(val *InstanceResourceList) *NullableInstanceResourceList {
	return &NullableInstanceResourceList{value: val, isSet: true}
}

func (v NullableInstanceResourceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceResourceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


