/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SyntaxTypeEnum * `0` - 其他 * `1` - DDL * `2` - DML * `3` - 离线导出工单
type SyntaxTypeEnum int32

// List of SyntaxTypeEnum
const (
	SYNTAXTYPEENUM__0 SyntaxTypeEnum = 0
	SYNTAXTYPEENUM__1 SyntaxTypeEnum = 1
	SYNTAXTYPEENUM__2 SyntaxTypeEnum = 2
	SYNTAXTYPEENUM__3 SyntaxTypeEnum = 3
)

// All allowed values of SyntaxTypeEnum enum
var AllowedSyntaxTypeEnumEnumValues = []SyntaxTypeEnum{
	0,
	1,
	2,
	3,
}

func (v *SyntaxTypeEnum) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SyntaxTypeEnum(value)
	for _, existing := range AllowedSyntaxTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SyntaxTypeEnum", value)
}

// NewSyntaxTypeEnumFromValue returns a pointer to a valid SyntaxTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSyntaxTypeEnumFromValue(v int32) (*SyntaxTypeEnum, error) {
	ev := SyntaxTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SyntaxTypeEnum: valid values are %v", v, AllowedSyntaxTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SyntaxTypeEnum) IsValid() bool {
	for _, existing := range AllowedSyntaxTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SyntaxTypeEnum value
func (v SyntaxTypeEnum) Ptr() *SyntaxTypeEnum {
	return &v
}

type NullableSyntaxTypeEnum struct {
	value *SyntaxTypeEnum
	isSet bool
}

func (v NullableSyntaxTypeEnum) Get() *SyntaxTypeEnum {
	return v.value
}

func (v *NullableSyntaxTypeEnum) Set(val *SyntaxTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableSyntaxTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableSyntaxTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyntaxTypeEnum(val *SyntaxTypeEnum) *NullableSyntaxTypeEnum {
	return &NullableSyntaxTypeEnum{value: val, isSet: true}
}

func (v NullableSyntaxTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyntaxTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

