/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LocatorExecutionSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocatorExecutionSummary{}

// LocatorExecutionSummary struct for LocatorExecutionSummary
type LocatorExecutionSummary struct {
	ProcessedInstanceCount int32 `json:"processed_instance_count"`
	SuccessfulInstanceCount int32 `json:"successful_instance_count"`
	FailedInstanceCount int32 `json:"failed_instance_count"`
	FailureReasons []LocatorFailureReason `json:"failure_reasons"`
}

type _LocatorExecutionSummary LocatorExecutionSummary

// NewLocatorExecutionSummary instantiates a new LocatorExecutionSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocatorExecutionSummary(processedInstanceCount int32, successfulInstanceCount int32, failedInstanceCount int32, failureReasons []LocatorFailureReason) *LocatorExecutionSummary {
	this := LocatorExecutionSummary{}
	this.ProcessedInstanceCount = processedInstanceCount
	this.SuccessfulInstanceCount = successfulInstanceCount
	this.FailedInstanceCount = failedInstanceCount
	this.FailureReasons = failureReasons
	return &this
}

// NewLocatorExecutionSummaryWithDefaults instantiates a new LocatorExecutionSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocatorExecutionSummaryWithDefaults() *LocatorExecutionSummary {
	this := LocatorExecutionSummary{}
	return &this
}

// GetProcessedInstanceCount returns the ProcessedInstanceCount field value
func (o *LocatorExecutionSummary) GetProcessedInstanceCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProcessedInstanceCount
}

// GetProcessedInstanceCountOk returns a tuple with the ProcessedInstanceCount field value
// and a boolean to check if the value has been set.
func (o *LocatorExecutionSummary) GetProcessedInstanceCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessedInstanceCount, true
}

// SetProcessedInstanceCount sets field value
func (o *LocatorExecutionSummary) SetProcessedInstanceCount(v int32) {
	o.ProcessedInstanceCount = v
}

// GetSuccessfulInstanceCount returns the SuccessfulInstanceCount field value
func (o *LocatorExecutionSummary) GetSuccessfulInstanceCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SuccessfulInstanceCount
}

// GetSuccessfulInstanceCountOk returns a tuple with the SuccessfulInstanceCount field value
// and a boolean to check if the value has been set.
func (o *LocatorExecutionSummary) GetSuccessfulInstanceCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessfulInstanceCount, true
}

// SetSuccessfulInstanceCount sets field value
func (o *LocatorExecutionSummary) SetSuccessfulInstanceCount(v int32) {
	o.SuccessfulInstanceCount = v
}

// GetFailedInstanceCount returns the FailedInstanceCount field value
func (o *LocatorExecutionSummary) GetFailedInstanceCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FailedInstanceCount
}

// GetFailedInstanceCountOk returns a tuple with the FailedInstanceCount field value
// and a boolean to check if the value has been set.
func (o *LocatorExecutionSummary) GetFailedInstanceCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailedInstanceCount, true
}

// SetFailedInstanceCount sets field value
func (o *LocatorExecutionSummary) SetFailedInstanceCount(v int32) {
	o.FailedInstanceCount = v
}

// GetFailureReasons returns the FailureReasons field value
func (o *LocatorExecutionSummary) GetFailureReasons() []LocatorFailureReason {
	if o == nil {
		var ret []LocatorFailureReason
		return ret
	}

	return o.FailureReasons
}

// GetFailureReasonsOk returns a tuple with the FailureReasons field value
// and a boolean to check if the value has been set.
func (o *LocatorExecutionSummary) GetFailureReasonsOk() ([]LocatorFailureReason, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailureReasons, true
}

// SetFailureReasons sets field value
func (o *LocatorExecutionSummary) SetFailureReasons(v []LocatorFailureReason) {
	o.FailureReasons = v
}

func (o LocatorExecutionSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocatorExecutionSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["processed_instance_count"] = o.ProcessedInstanceCount
	toSerialize["successful_instance_count"] = o.SuccessfulInstanceCount
	toSerialize["failed_instance_count"] = o.FailedInstanceCount
	toSerialize["failure_reasons"] = o.FailureReasons
	return toSerialize, nil
}

func (o *LocatorExecutionSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"processed_instance_count",
		"successful_instance_count",
		"failed_instance_count",
		"failure_reasons",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLocatorExecutionSummary := _LocatorExecutionSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLocatorExecutionSummary)

	if err != nil {
		return err
	}

	*o = LocatorExecutionSummary(varLocatorExecutionSummary)

	return err
}

type NullableLocatorExecutionSummary struct {
	value *LocatorExecutionSummary
	isSet bool
}

func (v NullableLocatorExecutionSummary) Get() *LocatorExecutionSummary {
	return v.value
}

func (v *NullableLocatorExecutionSummary) Set(val *LocatorExecutionSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableLocatorExecutionSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableLocatorExecutionSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocatorExecutionSummary(val *LocatorExecutionSummary) *NullableLocatorExecutionSummary {
	return &NullableLocatorExecutionSummary{value: val, isSet: true}
}

func (v NullableLocatorExecutionSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocatorExecutionSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


