/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenVerify type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenVerify{}

// TokenVerify struct for TokenVerify
type TokenVerify struct {
	Token string `json:"token"`
}

type _TokenVerify TokenVerify

// NewTokenVerify instantiates a new TokenVerify object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenVerify(token string) *TokenVerify {
	this := TokenVerify{}
	this.Token = token
	return &this
}

// NewTokenVerifyWithDefaults instantiates a new TokenVerify object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenVerifyWithDefaults() *TokenVerify {
	this := TokenVerify{}
	return &this
}

// GetToken returns the Token field value
func (o *TokenVerify) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *TokenVerify) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *TokenVerify) SetToken(v string) {
	o.Token = v
}

func (o TokenVerify) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenVerify) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *TokenVerify) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenVerify := _TokenVerify{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenVerify)

	if err != nil {
		return err
	}

	*o = TokenVerify(varTokenVerify)

	return err
}

type NullableTokenVerify struct {
	value *TokenVerify
	isSet bool
}

func (v NullableTokenVerify) Get() *TokenVerify {
	return v.value
}

func (v *NullableTokenVerify) Set(val *TokenVerify) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenVerify) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenVerify) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenVerify(val *TokenVerify) *NullableTokenVerify {
	return &NullableTokenVerify{value: val, isSet: true}
}

func (v NullableTokenVerify) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenVerify) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


