/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowLog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowLog{}

// WorkflowLog struct for WorkflowLog
type WorkflowLog struct {
	WorkflowId int32 `json:"workflow_id"`
	WorkflowType WorkflowLogWorkflowTypeEnum `json:"workflow_type"`
}

type _WorkflowLog WorkflowLog

// NewWorkflowLog instantiates a new WorkflowLog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowLog(workflowId int32, workflowType WorkflowLogWorkflowTypeEnum) *WorkflowLog {
	this := WorkflowLog{}
	this.WorkflowId = workflowId
	this.WorkflowType = workflowType
	return &this
}

// NewWorkflowLogWithDefaults instantiates a new WorkflowLog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowLogWithDefaults() *WorkflowLog {
	this := WorkflowLog{}
	return &this
}

// GetWorkflowId returns the WorkflowId field value
func (o *WorkflowLog) GetWorkflowId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
func (o *WorkflowLog) GetWorkflowIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowId, true
}

// SetWorkflowId sets field value
func (o *WorkflowLog) SetWorkflowId(v int32) {
	o.WorkflowId = v
}

// GetWorkflowType returns the WorkflowType field value
func (o *WorkflowLog) GetWorkflowType() WorkflowLogWorkflowTypeEnum {
	if o == nil {
		var ret WorkflowLogWorkflowTypeEnum
		return ret
	}

	return o.WorkflowType
}

// GetWorkflowTypeOk returns a tuple with the WorkflowType field value
// and a boolean to check if the value has been set.
func (o *WorkflowLog) GetWorkflowTypeOk() (*WorkflowLogWorkflowTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowType, true
}

// SetWorkflowType sets field value
func (o *WorkflowLog) SetWorkflowType(v WorkflowLogWorkflowTypeEnum) {
	o.WorkflowType = v
}

func (o WorkflowLog) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowLog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workflow_id"] = o.WorkflowId
	toSerialize["workflow_type"] = o.WorkflowType
	return toSerialize, nil
}

func (o *WorkflowLog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workflow_id",
		"workflow_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowLog := _WorkflowLog{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowLog)

	if err != nil {
		return err
	}

	*o = WorkflowLog(varWorkflowLog)

	return err
}

type NullableWorkflowLog struct {
	value *WorkflowLog
	isSet bool
}

func (v NullableWorkflowLog) Get() *WorkflowLog {
	return v.value
}

func (v *NullableWorkflowLog) Set(val *WorkflowLog) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowLog) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowLog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowLog(val *WorkflowLog) *NullableWorkflowLog {
	return &NullableWorkflowLog{value: val, isSet: true}
}

func (v NullableWorkflowLog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowLog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


