/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Instance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Instance{}

// Instance struct for Instance
type Instance struct {
	Id int32 `json:"id"`
	InstanceName string `json:"instance_name"`
	Type TypeA85Enum `json:"type"`
	DbType DbTypeEnum `json:"db_type"`
	Mode *string `json:"mode,omitempty"`
	Host string `json:"host"`
	Port *int32 `json:"port,omitempty"`
	User *string `json:"user,omitempty"`
	Password *string `json:"password,omitempty"`
	IsSsl *bool `json:"is_ssl,omitempty"`
	VerifySsl *bool `json:"verify_ssl,omitempty"`
	DbName *string `json:"db_name,omitempty"`
	// 正则表达式。示例：^(test_db|dmp_db|za.*)$。Redis示例: ^(0|4|6|11|12|13)$
	ShowDbNameRegex *string `json:"show_db_name_regex,omitempty"`
	// 正则表达式。隐藏大于显示，此规则优先。
	DeniedDbNameRegex *string `json:"denied_db_name_regex,omitempty"`
	Charset *string `json:"charset,omitempty"`
	ServiceName NullableString `json:"service_name,omitempty"`
	Sid NullableString `json:"sid,omitempty"`
	CreateTime time.Time `json:"create_time"`
	UpdateTime time.Time `json:"update_time"`
	Tunnel NullableInt32 `json:"tunnel,omitempty"`
	ResourceGroup []int32 `json:"resource_group,omitempty"`
	InstanceTag []int32 `json:"instance_tag,omitempty"`
}

type _Instance Instance

// NewInstance instantiates a new Instance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstance(id int32, instanceName string, type_ TypeA85Enum, dbType DbTypeEnum, host string, createTime time.Time, updateTime time.Time) *Instance {
	this := Instance{}
	this.Id = id
	this.InstanceName = instanceName
	this.Type = type_
	this.DbType = dbType
	this.Host = host
	this.CreateTime = createTime
	this.UpdateTime = updateTime
	return &this
}

// NewInstanceWithDefaults instantiates a new Instance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceWithDefaults() *Instance {
	this := Instance{}
	return &this
}

// GetId returns the Id field value
func (o *Instance) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Instance) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Instance) SetId(v int32) {
	o.Id = v
}

// GetInstanceName returns the InstanceName field value
func (o *Instance) GetInstanceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceName
}

// GetInstanceNameOk returns a tuple with the InstanceName field value
// and a boolean to check if the value has been set.
func (o *Instance) GetInstanceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceName, true
}

// SetInstanceName sets field value
func (o *Instance) SetInstanceName(v string) {
	o.InstanceName = v
}

// GetType returns the Type field value
func (o *Instance) GetType() TypeA85Enum {
	if o == nil {
		var ret TypeA85Enum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Instance) GetTypeOk() (*TypeA85Enum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Instance) SetType(v TypeA85Enum) {
	o.Type = v
}

// GetDbType returns the DbType field value
func (o *Instance) GetDbType() DbTypeEnum {
	if o == nil {
		var ret DbTypeEnum
		return ret
	}

	return o.DbType
}

// GetDbTypeOk returns a tuple with the DbType field value
// and a boolean to check if the value has been set.
func (o *Instance) GetDbTypeOk() (*DbTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DbType, true
}

// SetDbType sets field value
func (o *Instance) SetDbType(v DbTypeEnum) {
	o.DbType = v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *Instance) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *Instance) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *Instance) SetMode(v string) {
	o.Mode = &v
}

// GetHost returns the Host field value
func (o *Instance) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *Instance) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *Instance) SetHost(v string) {
	o.Host = v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *Instance) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *Instance) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *Instance) SetPort(v int32) {
	o.Port = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *Instance) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *Instance) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *Instance) SetUser(v string) {
	o.User = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *Instance) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *Instance) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *Instance) SetPassword(v string) {
	o.Password = &v
}

// GetIsSsl returns the IsSsl field value if set, zero value otherwise.
func (o *Instance) GetIsSsl() bool {
	if o == nil || IsNil(o.IsSsl) {
		var ret bool
		return ret
	}
	return *o.IsSsl
}

// GetIsSslOk returns a tuple with the IsSsl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetIsSslOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSsl) {
		return nil, false
	}
	return o.IsSsl, true
}

// HasIsSsl returns a boolean if a field has been set.
func (o *Instance) HasIsSsl() bool {
	if o != nil && !IsNil(o.IsSsl) {
		return true
	}

	return false
}

// SetIsSsl gets a reference to the given bool and assigns it to the IsSsl field.
func (o *Instance) SetIsSsl(v bool) {
	o.IsSsl = &v
}

// GetVerifySsl returns the VerifySsl field value if set, zero value otherwise.
func (o *Instance) GetVerifySsl() bool {
	if o == nil || IsNil(o.VerifySsl) {
		var ret bool
		return ret
	}
	return *o.VerifySsl
}

// GetVerifySslOk returns a tuple with the VerifySsl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetVerifySslOk() (*bool, bool) {
	if o == nil || IsNil(o.VerifySsl) {
		return nil, false
	}
	return o.VerifySsl, true
}

// HasVerifySsl returns a boolean if a field has been set.
func (o *Instance) HasVerifySsl() bool {
	if o != nil && !IsNil(o.VerifySsl) {
		return true
	}

	return false
}

// SetVerifySsl gets a reference to the given bool and assigns it to the VerifySsl field.
func (o *Instance) SetVerifySsl(v bool) {
	o.VerifySsl = &v
}

// GetDbName returns the DbName field value if set, zero value otherwise.
func (o *Instance) GetDbName() string {
	if o == nil || IsNil(o.DbName) {
		var ret string
		return ret
	}
	return *o.DbName
}

// GetDbNameOk returns a tuple with the DbName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetDbNameOk() (*string, bool) {
	if o == nil || IsNil(o.DbName) {
		return nil, false
	}
	return o.DbName, true
}

// HasDbName returns a boolean if a field has been set.
func (o *Instance) HasDbName() bool {
	if o != nil && !IsNil(o.DbName) {
		return true
	}

	return false
}

// SetDbName gets a reference to the given string and assigns it to the DbName field.
func (o *Instance) SetDbName(v string) {
	o.DbName = &v
}

// GetShowDbNameRegex returns the ShowDbNameRegex field value if set, zero value otherwise.
func (o *Instance) GetShowDbNameRegex() string {
	if o == nil || IsNil(o.ShowDbNameRegex) {
		var ret string
		return ret
	}
	return *o.ShowDbNameRegex
}

// GetShowDbNameRegexOk returns a tuple with the ShowDbNameRegex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetShowDbNameRegexOk() (*string, bool) {
	if o == nil || IsNil(o.ShowDbNameRegex) {
		return nil, false
	}
	return o.ShowDbNameRegex, true
}

// HasShowDbNameRegex returns a boolean if a field has been set.
func (o *Instance) HasShowDbNameRegex() bool {
	if o != nil && !IsNil(o.ShowDbNameRegex) {
		return true
	}

	return false
}

// SetShowDbNameRegex gets a reference to the given string and assigns it to the ShowDbNameRegex field.
func (o *Instance) SetShowDbNameRegex(v string) {
	o.ShowDbNameRegex = &v
}

// GetDeniedDbNameRegex returns the DeniedDbNameRegex field value if set, zero value otherwise.
func (o *Instance) GetDeniedDbNameRegex() string {
	if o == nil || IsNil(o.DeniedDbNameRegex) {
		var ret string
		return ret
	}
	return *o.DeniedDbNameRegex
}

// GetDeniedDbNameRegexOk returns a tuple with the DeniedDbNameRegex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetDeniedDbNameRegexOk() (*string, bool) {
	if o == nil || IsNil(o.DeniedDbNameRegex) {
		return nil, false
	}
	return o.DeniedDbNameRegex, true
}

// HasDeniedDbNameRegex returns a boolean if a field has been set.
func (o *Instance) HasDeniedDbNameRegex() bool {
	if o != nil && !IsNil(o.DeniedDbNameRegex) {
		return true
	}

	return false
}

// SetDeniedDbNameRegex gets a reference to the given string and assigns it to the DeniedDbNameRegex field.
func (o *Instance) SetDeniedDbNameRegex(v string) {
	o.DeniedDbNameRegex = &v
}

// GetCharset returns the Charset field value if set, zero value otherwise.
func (o *Instance) GetCharset() string {
	if o == nil || IsNil(o.Charset) {
		var ret string
		return ret
	}
	return *o.Charset
}

// GetCharsetOk returns a tuple with the Charset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetCharsetOk() (*string, bool) {
	if o == nil || IsNil(o.Charset) {
		return nil, false
	}
	return o.Charset, true
}

// HasCharset returns a boolean if a field has been set.
func (o *Instance) HasCharset() bool {
	if o != nil && !IsNil(o.Charset) {
		return true
	}

	return false
}

// SetCharset gets a reference to the given string and assigns it to the Charset field.
func (o *Instance) SetCharset(v string) {
	o.Charset = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName.Get()) {
		var ret string
		return ret
	}
	return *o.ServiceName.Get()
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceName.Get(), o.ServiceName.IsSet()
}

// HasServiceName returns a boolean if a field has been set.
func (o *Instance) HasServiceName() bool {
	if o != nil && o.ServiceName.IsSet() {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given NullableString and assigns it to the ServiceName field.
func (o *Instance) SetServiceName(v string) {
	o.ServiceName.Set(&v)
}
// SetServiceNameNil sets the value for ServiceName to be an explicit nil
func (o *Instance) SetServiceNameNil() {
	o.ServiceName.Set(nil)
}

// UnsetServiceName ensures that no value is present for ServiceName, not even an explicit nil
func (o *Instance) UnsetServiceName() {
	o.ServiceName.Unset()
}

// GetSid returns the Sid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetSid() string {
	if o == nil || IsNil(o.Sid.Get()) {
		var ret string
		return ret
	}
	return *o.Sid.Get()
}

// GetSidOk returns a tuple with the Sid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetSidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sid.Get(), o.Sid.IsSet()
}

// HasSid returns a boolean if a field has been set.
func (o *Instance) HasSid() bool {
	if o != nil && o.Sid.IsSet() {
		return true
	}

	return false
}

// SetSid gets a reference to the given NullableString and assigns it to the Sid field.
func (o *Instance) SetSid(v string) {
	o.Sid.Set(&v)
}
// SetSidNil sets the value for Sid to be an explicit nil
func (o *Instance) SetSidNil() {
	o.Sid.Set(nil)
}

// UnsetSid ensures that no value is present for Sid, not even an explicit nil
func (o *Instance) UnsetSid() {
	o.Sid.Unset()
}

// GetCreateTime returns the CreateTime field value
func (o *Instance) GetCreateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value
// and a boolean to check if the value has been set.
func (o *Instance) GetCreateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreateTime, true
}

// SetCreateTime sets field value
func (o *Instance) SetCreateTime(v time.Time) {
	o.CreateTime = v
}

// GetUpdateTime returns the UpdateTime field value
func (o *Instance) GetUpdateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value
// and a boolean to check if the value has been set.
func (o *Instance) GetUpdateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdateTime, true
}

// SetUpdateTime sets field value
func (o *Instance) SetUpdateTime(v time.Time) {
	o.UpdateTime = v
}

// GetTunnel returns the Tunnel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetTunnel() int32 {
	if o == nil || IsNil(o.Tunnel.Get()) {
		var ret int32
		return ret
	}
	return *o.Tunnel.Get()
}

// GetTunnelOk returns a tuple with the Tunnel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetTunnelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tunnel.Get(), o.Tunnel.IsSet()
}

// HasTunnel returns a boolean if a field has been set.
func (o *Instance) HasTunnel() bool {
	if o != nil && o.Tunnel.IsSet() {
		return true
	}

	return false
}

// SetTunnel gets a reference to the given NullableInt32 and assigns it to the Tunnel field.
func (o *Instance) SetTunnel(v int32) {
	o.Tunnel.Set(&v)
}
// SetTunnelNil sets the value for Tunnel to be an explicit nil
func (o *Instance) SetTunnelNil() {
	o.Tunnel.Set(nil)
}

// UnsetTunnel ensures that no value is present for Tunnel, not even an explicit nil
func (o *Instance) UnsetTunnel() {
	o.Tunnel.Unset()
}

// GetResourceGroup returns the ResourceGroup field value if set, zero value otherwise.
func (o *Instance) GetResourceGroup() []int32 {
	if o == nil || IsNil(o.ResourceGroup) {
		var ret []int32
		return ret
	}
	return o.ResourceGroup
}

// GetResourceGroupOk returns a tuple with the ResourceGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetResourceGroupOk() ([]int32, bool) {
	if o == nil || IsNil(o.ResourceGroup) {
		return nil, false
	}
	return o.ResourceGroup, true
}

// HasResourceGroup returns a boolean if a field has been set.
func (o *Instance) HasResourceGroup() bool {
	if o != nil && !IsNil(o.ResourceGroup) {
		return true
	}

	return false
}

// SetResourceGroup gets a reference to the given []int32 and assigns it to the ResourceGroup field.
func (o *Instance) SetResourceGroup(v []int32) {
	o.ResourceGroup = v
}

// GetInstanceTag returns the InstanceTag field value if set, zero value otherwise.
func (o *Instance) GetInstanceTag() []int32 {
	if o == nil || IsNil(o.InstanceTag) {
		var ret []int32
		return ret
	}
	return o.InstanceTag
}

// GetInstanceTagOk returns a tuple with the InstanceTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetInstanceTagOk() ([]int32, bool) {
	if o == nil || IsNil(o.InstanceTag) {
		return nil, false
	}
	return o.InstanceTag, true
}

// HasInstanceTag returns a boolean if a field has been set.
func (o *Instance) HasInstanceTag() bool {
	if o != nil && !IsNil(o.InstanceTag) {
		return true
	}

	return false
}

// SetInstanceTag gets a reference to the given []int32 and assigns it to the InstanceTag field.
func (o *Instance) SetInstanceTag(v []int32) {
	o.InstanceTag = v
}

func (o Instance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Instance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["instance_name"] = o.InstanceName
	toSerialize["type"] = o.Type
	toSerialize["db_type"] = o.DbType
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	toSerialize["host"] = o.Host
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.IsSsl) {
		toSerialize["is_ssl"] = o.IsSsl
	}
	if !IsNil(o.VerifySsl) {
		toSerialize["verify_ssl"] = o.VerifySsl
	}
	if !IsNil(o.DbName) {
		toSerialize["db_name"] = o.DbName
	}
	if !IsNil(o.ShowDbNameRegex) {
		toSerialize["show_db_name_regex"] = o.ShowDbNameRegex
	}
	if !IsNil(o.DeniedDbNameRegex) {
		toSerialize["denied_db_name_regex"] = o.DeniedDbNameRegex
	}
	if !IsNil(o.Charset) {
		toSerialize["charset"] = o.Charset
	}
	if o.ServiceName.IsSet() {
		toSerialize["service_name"] = o.ServiceName.Get()
	}
	if o.Sid.IsSet() {
		toSerialize["sid"] = o.Sid.Get()
	}
	toSerialize["create_time"] = o.CreateTime
	toSerialize["update_time"] = o.UpdateTime
	if o.Tunnel.IsSet() {
		toSerialize["tunnel"] = o.Tunnel.Get()
	}
	if !IsNil(o.ResourceGroup) {
		toSerialize["resource_group"] = o.ResourceGroup
	}
	if !IsNil(o.InstanceTag) {
		toSerialize["instance_tag"] = o.InstanceTag
	}
	return toSerialize, nil
}

func (o *Instance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"instance_name",
		"type",
		"db_type",
		"host",
		"create_time",
		"update_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstance := _Instance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstance)

	if err != nil {
		return err
	}

	*o = Instance(varInstance)

	return err
}

type NullableInstance struct {
	value *Instance
	isSet bool
}

func (v NullableInstance) Get() *Instance {
	return v.value
}

func (v *NullableInstance) Set(val *Instance) {
	v.value = val
	v.isSet = true
}

func (v NullableInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstance(val *Instance) *NullableInstance {
	return &NullableInstance{value: val, isSet: true}
}

func (v NullableInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


