/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// EnableEnum * `true` - true * `false` - false
type EnableEnum string

// List of EnableEnum
const (
	ENABLEENUM_TRUE EnableEnum = "true"
	ENABLEENUM_FALSE EnableEnum = "false"
)

// All allowed values of EnableEnum enum
var AllowedEnableEnumEnumValues = []EnableEnum{
	"true",
	"false",
}

func (v *EnableEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnableEnum(value)
	for _, existing := range AllowedEnableEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EnableEnum", value)
}

// NewEnableEnumFromValue returns a pointer to a valid EnableEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnableEnumFromValue(v string) (*EnableEnum, error) {
	ev := EnableEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnableEnum: valid values are %v", v, AllowedEnableEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnableEnum) IsValid() bool {
	for _, existing := range AllowedEnableEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EnableEnum value
func (v EnableEnum) Ptr() *EnableEnum {
	return &v
}

type NullableEnableEnum struct {
	value *EnableEnum
	isSet bool
}

func (v NullableEnableEnum) Get() *EnableEnum {
	return v.value
}

func (v *NullableEnableEnum) Set(val *EnableEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableEnableEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableEnableEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnableEnum(val *EnableEnum) *NullableEnableEnum {
	return &NullableEnableEnum{value: val, isSet: true}
}

func (v NullableEnableEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnableEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

