/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TypeA85Enum * `master` - 主库 * `slave` - 从库
type TypeA85Enum string

// List of TypeA85Enum
const (
	TYPEA85ENUM_MASTER TypeA85Enum = "master"
	TYPEA85ENUM_SLAVE TypeA85Enum = "slave"
)

// All allowed values of TypeA85Enum enum
var AllowedTypeA85EnumEnumValues = []TypeA85Enum{
	"master",
	"slave",
}

func (v *TypeA85Enum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TypeA85Enum(value)
	for _, existing := range AllowedTypeA85EnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TypeA85Enum", value)
}

// NewTypeA85EnumFromValue returns a pointer to a valid TypeA85Enum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTypeA85EnumFromValue(v string) (*TypeA85Enum, error) {
	ev := TypeA85Enum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TypeA85Enum: valid values are %v", v, AllowedTypeA85EnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TypeA85Enum) IsValid() bool {
	for _, existing := range AllowedTypeA85EnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TypeA85Enum value
func (v TypeA85Enum) Ptr() *TypeA85Enum {
	return &v
}

type NullableTypeA85Enum struct {
	value *TypeA85Enum
	isSet bool
}

func (v NullableTypeA85Enum) Get() *TypeA85Enum {
	return v.value
}

func (v *NullableTypeA85Enum) Set(val *TypeA85Enum) {
	v.value = val
	v.isSet = true
}

func (v NullableTypeA85Enum) IsSet() bool {
	return v.isSet
}

func (v *NullableTypeA85Enum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypeA85Enum(val *TypeA85Enum) *NullableTypeA85Enum {
	return &NullableTypeA85Enum{value: val, isSet: true}
}

func (v NullableTypeA85Enum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypeA85Enum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

