/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// IsOfflineExportEnum * `0` - 否 * `1` - 是
type IsOfflineExportEnum int32

// List of IsOfflineExportEnum
const (
	ISOFFLINEEXPORTENUM__0 IsOfflineExportEnum = 0
	ISOFFLINEEXPORTENUM__1 IsOfflineExportEnum = 1
)

// All allowed values of IsOfflineExportEnum enum
var AllowedIsOfflineExportEnumEnumValues = []IsOfflineExportEnum{
	0,
	1,
}

func (v *IsOfflineExportEnum) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IsOfflineExportEnum(value)
	for _, existing := range AllowedIsOfflineExportEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IsOfflineExportEnum", value)
}

// NewIsOfflineExportEnumFromValue returns a pointer to a valid IsOfflineExportEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIsOfflineExportEnumFromValue(v int32) (*IsOfflineExportEnum, error) {
	ev := IsOfflineExportEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IsOfflineExportEnum: valid values are %v", v, AllowedIsOfflineExportEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IsOfflineExportEnum) IsValid() bool {
	for _, existing := range AllowedIsOfflineExportEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IsOfflineExportEnum value
func (v IsOfflineExportEnum) Ptr() *IsOfflineExportEnum {
	return &v
}

type NullableIsOfflineExportEnum struct {
	value *IsOfflineExportEnum
	isSet bool
}

func (v NullableIsOfflineExportEnum) Get() *IsOfflineExportEnum {
	return v.value
}

func (v *NullableIsOfflineExportEnum) Set(val *IsOfflineExportEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableIsOfflineExportEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableIsOfflineExportEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIsOfflineExportEnum(val *IsOfflineExportEnum) *NullableIsOfflineExportEnum {
	return &NullableIsOfflineExportEnum{value: val, isSet: true}
}

func (v NullableIsOfflineExportEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIsOfflineExportEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

