/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstanceResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceResource{}

// InstanceResource struct for InstanceResource
type InstanceResource struct {
	InstanceId int32 `json:"instance_id"`
	ResourceType ResourceTypeEnum `json:"resource_type"`
	DbName *string `json:"db_name,omitempty"`
	SchemaName *string `json:"schema_name,omitempty"`
	TbName *string `json:"tb_name,omitempty"`
}

type _InstanceResource InstanceResource

// NewInstanceResource instantiates a new InstanceResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceResource(instanceId int32, resourceType ResourceTypeEnum) *InstanceResource {
	this := InstanceResource{}
	this.InstanceId = instanceId
	this.ResourceType = resourceType
	return &this
}

// NewInstanceResourceWithDefaults instantiates a new InstanceResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceResourceWithDefaults() *InstanceResource {
	this := InstanceResource{}
	return &this
}

// GetInstanceId returns the InstanceId field value
func (o *InstanceResource) GetInstanceId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value
// and a boolean to check if the value has been set.
func (o *InstanceResource) GetInstanceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceId, true
}

// SetInstanceId sets field value
func (o *InstanceResource) SetInstanceId(v int32) {
	o.InstanceId = v
}

// GetResourceType returns the ResourceType field value
func (o *InstanceResource) GetResourceType() ResourceTypeEnum {
	if o == nil {
		var ret ResourceTypeEnum
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *InstanceResource) GetResourceTypeOk() (*ResourceTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *InstanceResource) SetResourceType(v ResourceTypeEnum) {
	o.ResourceType = v
}

// GetDbName returns the DbName field value if set, zero value otherwise.
func (o *InstanceResource) GetDbName() string {
	if o == nil || IsNil(o.DbName) {
		var ret string
		return ret
	}
	return *o.DbName
}

// GetDbNameOk returns a tuple with the DbName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceResource) GetDbNameOk() (*string, bool) {
	if o == nil || IsNil(o.DbName) {
		return nil, false
	}
	return o.DbName, true
}

// HasDbName returns a boolean if a field has been set.
func (o *InstanceResource) HasDbName() bool {
	if o != nil && !IsNil(o.DbName) {
		return true
	}

	return false
}

// SetDbName gets a reference to the given string and assigns it to the DbName field.
func (o *InstanceResource) SetDbName(v string) {
	o.DbName = &v
}

// GetSchemaName returns the SchemaName field value if set, zero value otherwise.
func (o *InstanceResource) GetSchemaName() string {
	if o == nil || IsNil(o.SchemaName) {
		var ret string
		return ret
	}
	return *o.SchemaName
}

// GetSchemaNameOk returns a tuple with the SchemaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceResource) GetSchemaNameOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaName) {
		return nil, false
	}
	return o.SchemaName, true
}

// HasSchemaName returns a boolean if a field has been set.
func (o *InstanceResource) HasSchemaName() bool {
	if o != nil && !IsNil(o.SchemaName) {
		return true
	}

	return false
}

// SetSchemaName gets a reference to the given string and assigns it to the SchemaName field.
func (o *InstanceResource) SetSchemaName(v string) {
	o.SchemaName = &v
}

// GetTbName returns the TbName field value if set, zero value otherwise.
func (o *InstanceResource) GetTbName() string {
	if o == nil || IsNil(o.TbName) {
		var ret string
		return ret
	}
	return *o.TbName
}

// GetTbNameOk returns a tuple with the TbName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceResource) GetTbNameOk() (*string, bool) {
	if o == nil || IsNil(o.TbName) {
		return nil, false
	}
	return o.TbName, true
}

// HasTbName returns a boolean if a field has been set.
func (o *InstanceResource) HasTbName() bool {
	if o != nil && !IsNil(o.TbName) {
		return true
	}

	return false
}

// SetTbName gets a reference to the given string and assigns it to the TbName field.
func (o *InstanceResource) SetTbName(v string) {
	o.TbName = &v
}

func (o InstanceResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instance_id"] = o.InstanceId
	toSerialize["resource_type"] = o.ResourceType
	if !IsNil(o.DbName) {
		toSerialize["db_name"] = o.DbName
	}
	if !IsNil(o.SchemaName) {
		toSerialize["schema_name"] = o.SchemaName
	}
	if !IsNil(o.TbName) {
		toSerialize["tb_name"] = o.TbName
	}
	return toSerialize, nil
}

func (o *InstanceResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instance_id",
		"resource_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceResource := _InstanceResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceResource)

	if err != nil {
		return err
	}

	*o = InstanceResource(varInstanceResource)

	return err
}

type NullableInstanceResource struct {
	value *InstanceResource
	isSet bool
}

func (v NullableInstanceResource) Get() *InstanceResource {
	return v.value
}

func (v *NullableInstanceResource) Set(val *InstanceResource) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceResource) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceResource(val *InstanceResource) *NullableInstanceResource {
	return &NullableInstanceResource{value: val, isSet: true}
}

func (v NullableInstanceResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


