/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the InstanceDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceDetail{}

// InstanceDetail struct for InstanceDetail
type InstanceDetail struct {
	Id int32 `json:"id"`
	InstanceName *string `json:"instance_name,omitempty"`
	Type *TypeA85Enum `json:"type,omitempty"`
	DbType *DbTypeEnum `json:"db_type,omitempty"`
	Mode *string `json:"mode,omitempty"`
	Host *string `json:"host,omitempty"`
	Port *int32 `json:"port,omitempty"`
	User *string `json:"user,omitempty"`
	Password *string `json:"password,omitempty"`
	IsSsl *bool `json:"is_ssl,omitempty"`
	VerifySsl *bool `json:"verify_ssl,omitempty"`
	DbName *string `json:"db_name,omitempty"`
	// 正则表达式。示例：^(test_db|dmp_db|za.*)$。Redis示例: ^(0|4|6|11|12|13)$
	ShowDbNameRegex *string `json:"show_db_name_regex,omitempty"`
	// 正则表达式。隐藏大于显示，此规则优先。
	DeniedDbNameRegex *string `json:"denied_db_name_regex,omitempty"`
	Charset *string `json:"charset,omitempty"`
	ServiceName NullableString `json:"service_name,omitempty"`
	Sid NullableString `json:"sid,omitempty"`
	CreateTime time.Time `json:"create_time"`
	UpdateTime time.Time `json:"update_time"`
	Tunnel NullableInt32 `json:"tunnel,omitempty"`
	ResourceGroup []int32 `json:"resource_group,omitempty"`
	InstanceTag []int32 `json:"instance_tag,omitempty"`
}

type _InstanceDetail InstanceDetail

// NewInstanceDetail instantiates a new InstanceDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceDetail(id int32, createTime time.Time, updateTime time.Time) *InstanceDetail {
	this := InstanceDetail{}
	this.Id = id
	this.CreateTime = createTime
	this.UpdateTime = updateTime
	return &this
}

// NewInstanceDetailWithDefaults instantiates a new InstanceDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceDetailWithDefaults() *InstanceDetail {
	this := InstanceDetail{}
	return &this
}

// GetId returns the Id field value
func (o *InstanceDetail) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InstanceDetail) SetId(v int32) {
	o.Id = v
}

// GetInstanceName returns the InstanceName field value if set, zero value otherwise.
func (o *InstanceDetail) GetInstanceName() string {
	if o == nil || IsNil(o.InstanceName) {
		var ret string
		return ret
	}
	return *o.InstanceName
}

// GetInstanceNameOk returns a tuple with the InstanceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetInstanceNameOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceName) {
		return nil, false
	}
	return o.InstanceName, true
}

// HasInstanceName returns a boolean if a field has been set.
func (o *InstanceDetail) HasInstanceName() bool {
	if o != nil && !IsNil(o.InstanceName) {
		return true
	}

	return false
}

// SetInstanceName gets a reference to the given string and assigns it to the InstanceName field.
func (o *InstanceDetail) SetInstanceName(v string) {
	o.InstanceName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *InstanceDetail) GetType() TypeA85Enum {
	if o == nil || IsNil(o.Type) {
		var ret TypeA85Enum
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetTypeOk() (*TypeA85Enum, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *InstanceDetail) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given TypeA85Enum and assigns it to the Type field.
func (o *InstanceDetail) SetType(v TypeA85Enum) {
	o.Type = &v
}

// GetDbType returns the DbType field value if set, zero value otherwise.
func (o *InstanceDetail) GetDbType() DbTypeEnum {
	if o == nil || IsNil(o.DbType) {
		var ret DbTypeEnum
		return ret
	}
	return *o.DbType
}

// GetDbTypeOk returns a tuple with the DbType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetDbTypeOk() (*DbTypeEnum, bool) {
	if o == nil || IsNil(o.DbType) {
		return nil, false
	}
	return o.DbType, true
}

// HasDbType returns a boolean if a field has been set.
func (o *InstanceDetail) HasDbType() bool {
	if o != nil && !IsNil(o.DbType) {
		return true
	}

	return false
}

// SetDbType gets a reference to the given DbTypeEnum and assigns it to the DbType field.
func (o *InstanceDetail) SetDbType(v DbTypeEnum) {
	o.DbType = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *InstanceDetail) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *InstanceDetail) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *InstanceDetail) SetMode(v string) {
	o.Mode = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *InstanceDetail) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *InstanceDetail) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *InstanceDetail) SetHost(v string) {
	o.Host = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *InstanceDetail) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *InstanceDetail) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *InstanceDetail) SetPort(v int32) {
	o.Port = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *InstanceDetail) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *InstanceDetail) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *InstanceDetail) SetUser(v string) {
	o.User = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *InstanceDetail) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *InstanceDetail) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *InstanceDetail) SetPassword(v string) {
	o.Password = &v
}

// GetIsSsl returns the IsSsl field value if set, zero value otherwise.
func (o *InstanceDetail) GetIsSsl() bool {
	if o == nil || IsNil(o.IsSsl) {
		var ret bool
		return ret
	}
	return *o.IsSsl
}

// GetIsSslOk returns a tuple with the IsSsl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetIsSslOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSsl) {
		return nil, false
	}
	return o.IsSsl, true
}

// HasIsSsl returns a boolean if a field has been set.
func (o *InstanceDetail) HasIsSsl() bool {
	if o != nil && !IsNil(o.IsSsl) {
		return true
	}

	return false
}

// SetIsSsl gets a reference to the given bool and assigns it to the IsSsl field.
func (o *InstanceDetail) SetIsSsl(v bool) {
	o.IsSsl = &v
}

// GetVerifySsl returns the VerifySsl field value if set, zero value otherwise.
func (o *InstanceDetail) GetVerifySsl() bool {
	if o == nil || IsNil(o.VerifySsl) {
		var ret bool
		return ret
	}
	return *o.VerifySsl
}

// GetVerifySslOk returns a tuple with the VerifySsl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetVerifySslOk() (*bool, bool) {
	if o == nil || IsNil(o.VerifySsl) {
		return nil, false
	}
	return o.VerifySsl, true
}

// HasVerifySsl returns a boolean if a field has been set.
func (o *InstanceDetail) HasVerifySsl() bool {
	if o != nil && !IsNil(o.VerifySsl) {
		return true
	}

	return false
}

// SetVerifySsl gets a reference to the given bool and assigns it to the VerifySsl field.
func (o *InstanceDetail) SetVerifySsl(v bool) {
	o.VerifySsl = &v
}

// GetDbName returns the DbName field value if set, zero value otherwise.
func (o *InstanceDetail) GetDbName() string {
	if o == nil || IsNil(o.DbName) {
		var ret string
		return ret
	}
	return *o.DbName
}

// GetDbNameOk returns a tuple with the DbName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetDbNameOk() (*string, bool) {
	if o == nil || IsNil(o.DbName) {
		return nil, false
	}
	return o.DbName, true
}

// HasDbName returns a boolean if a field has been set.
func (o *InstanceDetail) HasDbName() bool {
	if o != nil && !IsNil(o.DbName) {
		return true
	}

	return false
}

// SetDbName gets a reference to the given string and assigns it to the DbName field.
func (o *InstanceDetail) SetDbName(v string) {
	o.DbName = &v
}

// GetShowDbNameRegex returns the ShowDbNameRegex field value if set, zero value otherwise.
func (o *InstanceDetail) GetShowDbNameRegex() string {
	if o == nil || IsNil(o.ShowDbNameRegex) {
		var ret string
		return ret
	}
	return *o.ShowDbNameRegex
}

// GetShowDbNameRegexOk returns a tuple with the ShowDbNameRegex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetShowDbNameRegexOk() (*string, bool) {
	if o == nil || IsNil(o.ShowDbNameRegex) {
		return nil, false
	}
	return o.ShowDbNameRegex, true
}

// HasShowDbNameRegex returns a boolean if a field has been set.
func (o *InstanceDetail) HasShowDbNameRegex() bool {
	if o != nil && !IsNil(o.ShowDbNameRegex) {
		return true
	}

	return false
}

// SetShowDbNameRegex gets a reference to the given string and assigns it to the ShowDbNameRegex field.
func (o *InstanceDetail) SetShowDbNameRegex(v string) {
	o.ShowDbNameRegex = &v
}

// GetDeniedDbNameRegex returns the DeniedDbNameRegex field value if set, zero value otherwise.
func (o *InstanceDetail) GetDeniedDbNameRegex() string {
	if o == nil || IsNil(o.DeniedDbNameRegex) {
		var ret string
		return ret
	}
	return *o.DeniedDbNameRegex
}

// GetDeniedDbNameRegexOk returns a tuple with the DeniedDbNameRegex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetDeniedDbNameRegexOk() (*string, bool) {
	if o == nil || IsNil(o.DeniedDbNameRegex) {
		return nil, false
	}
	return o.DeniedDbNameRegex, true
}

// HasDeniedDbNameRegex returns a boolean if a field has been set.
func (o *InstanceDetail) HasDeniedDbNameRegex() bool {
	if o != nil && !IsNil(o.DeniedDbNameRegex) {
		return true
	}

	return false
}

// SetDeniedDbNameRegex gets a reference to the given string and assigns it to the DeniedDbNameRegex field.
func (o *InstanceDetail) SetDeniedDbNameRegex(v string) {
	o.DeniedDbNameRegex = &v
}

// GetCharset returns the Charset field value if set, zero value otherwise.
func (o *InstanceDetail) GetCharset() string {
	if o == nil || IsNil(o.Charset) {
		var ret string
		return ret
	}
	return *o.Charset
}

// GetCharsetOk returns a tuple with the Charset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetCharsetOk() (*string, bool) {
	if o == nil || IsNil(o.Charset) {
		return nil, false
	}
	return o.Charset, true
}

// HasCharset returns a boolean if a field has been set.
func (o *InstanceDetail) HasCharset() bool {
	if o != nil && !IsNil(o.Charset) {
		return true
	}

	return false
}

// SetCharset gets a reference to the given string and assigns it to the Charset field.
func (o *InstanceDetail) SetCharset(v string) {
	o.Charset = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceDetail) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName.Get()) {
		var ret string
		return ret
	}
	return *o.ServiceName.Get()
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceDetail) GetServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceName.Get(), o.ServiceName.IsSet()
}

// HasServiceName returns a boolean if a field has been set.
func (o *InstanceDetail) HasServiceName() bool {
	if o != nil && o.ServiceName.IsSet() {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given NullableString and assigns it to the ServiceName field.
func (o *InstanceDetail) SetServiceName(v string) {
	o.ServiceName.Set(&v)
}
// SetServiceNameNil sets the value for ServiceName to be an explicit nil
func (o *InstanceDetail) SetServiceNameNil() {
	o.ServiceName.Set(nil)
}

// UnsetServiceName ensures that no value is present for ServiceName, not even an explicit nil
func (o *InstanceDetail) UnsetServiceName() {
	o.ServiceName.Unset()
}

// GetSid returns the Sid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceDetail) GetSid() string {
	if o == nil || IsNil(o.Sid.Get()) {
		var ret string
		return ret
	}
	return *o.Sid.Get()
}

// GetSidOk returns a tuple with the Sid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceDetail) GetSidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sid.Get(), o.Sid.IsSet()
}

// HasSid returns a boolean if a field has been set.
func (o *InstanceDetail) HasSid() bool {
	if o != nil && o.Sid.IsSet() {
		return true
	}

	return false
}

// SetSid gets a reference to the given NullableString and assigns it to the Sid field.
func (o *InstanceDetail) SetSid(v string) {
	o.Sid.Set(&v)
}
// SetSidNil sets the value for Sid to be an explicit nil
func (o *InstanceDetail) SetSidNil() {
	o.Sid.Set(nil)
}

// UnsetSid ensures that no value is present for Sid, not even an explicit nil
func (o *InstanceDetail) UnsetSid() {
	o.Sid.Unset()
}

// GetCreateTime returns the CreateTime field value
func (o *InstanceDetail) GetCreateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetCreateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreateTime, true
}

// SetCreateTime sets field value
func (o *InstanceDetail) SetCreateTime(v time.Time) {
	o.CreateTime = v
}

// GetUpdateTime returns the UpdateTime field value
func (o *InstanceDetail) GetUpdateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetUpdateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdateTime, true
}

// SetUpdateTime sets field value
func (o *InstanceDetail) SetUpdateTime(v time.Time) {
	o.UpdateTime = v
}

// GetTunnel returns the Tunnel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceDetail) GetTunnel() int32 {
	if o == nil || IsNil(o.Tunnel.Get()) {
		var ret int32
		return ret
	}
	return *o.Tunnel.Get()
}

// GetTunnelOk returns a tuple with the Tunnel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceDetail) GetTunnelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tunnel.Get(), o.Tunnel.IsSet()
}

// HasTunnel returns a boolean if a field has been set.
func (o *InstanceDetail) HasTunnel() bool {
	if o != nil && o.Tunnel.IsSet() {
		return true
	}

	return false
}

// SetTunnel gets a reference to the given NullableInt32 and assigns it to the Tunnel field.
func (o *InstanceDetail) SetTunnel(v int32) {
	o.Tunnel.Set(&v)
}
// SetTunnelNil sets the value for Tunnel to be an explicit nil
func (o *InstanceDetail) SetTunnelNil() {
	o.Tunnel.Set(nil)
}

// UnsetTunnel ensures that no value is present for Tunnel, not even an explicit nil
func (o *InstanceDetail) UnsetTunnel() {
	o.Tunnel.Unset()
}

// GetResourceGroup returns the ResourceGroup field value if set, zero value otherwise.
func (o *InstanceDetail) GetResourceGroup() []int32 {
	if o == nil || IsNil(o.ResourceGroup) {
		var ret []int32
		return ret
	}
	return o.ResourceGroup
}

// GetResourceGroupOk returns a tuple with the ResourceGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetResourceGroupOk() ([]int32, bool) {
	if o == nil || IsNil(o.ResourceGroup) {
		return nil, false
	}
	return o.ResourceGroup, true
}

// HasResourceGroup returns a boolean if a field has been set.
func (o *InstanceDetail) HasResourceGroup() bool {
	if o != nil && !IsNil(o.ResourceGroup) {
		return true
	}

	return false
}

// SetResourceGroup gets a reference to the given []int32 and assigns it to the ResourceGroup field.
func (o *InstanceDetail) SetResourceGroup(v []int32) {
	o.ResourceGroup = v
}

// GetInstanceTag returns the InstanceTag field value if set, zero value otherwise.
func (o *InstanceDetail) GetInstanceTag() []int32 {
	if o == nil || IsNil(o.InstanceTag) {
		var ret []int32
		return ret
	}
	return o.InstanceTag
}

// GetInstanceTagOk returns a tuple with the InstanceTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceDetail) GetInstanceTagOk() ([]int32, bool) {
	if o == nil || IsNil(o.InstanceTag) {
		return nil, false
	}
	return o.InstanceTag, true
}

// HasInstanceTag returns a boolean if a field has been set.
func (o *InstanceDetail) HasInstanceTag() bool {
	if o != nil && !IsNil(o.InstanceTag) {
		return true
	}

	return false
}

// SetInstanceTag gets a reference to the given []int32 and assigns it to the InstanceTag field.
func (o *InstanceDetail) SetInstanceTag(v []int32) {
	o.InstanceTag = v
}

func (o InstanceDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.InstanceName) {
		toSerialize["instance_name"] = o.InstanceName
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.DbType) {
		toSerialize["db_type"] = o.DbType
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.IsSsl) {
		toSerialize["is_ssl"] = o.IsSsl
	}
	if !IsNil(o.VerifySsl) {
		toSerialize["verify_ssl"] = o.VerifySsl
	}
	if !IsNil(o.DbName) {
		toSerialize["db_name"] = o.DbName
	}
	if !IsNil(o.ShowDbNameRegex) {
		toSerialize["show_db_name_regex"] = o.ShowDbNameRegex
	}
	if !IsNil(o.DeniedDbNameRegex) {
		toSerialize["denied_db_name_regex"] = o.DeniedDbNameRegex
	}
	if !IsNil(o.Charset) {
		toSerialize["charset"] = o.Charset
	}
	if o.ServiceName.IsSet() {
		toSerialize["service_name"] = o.ServiceName.Get()
	}
	if o.Sid.IsSet() {
		toSerialize["sid"] = o.Sid.Get()
	}
	toSerialize["create_time"] = o.CreateTime
	toSerialize["update_time"] = o.UpdateTime
	if o.Tunnel.IsSet() {
		toSerialize["tunnel"] = o.Tunnel.Get()
	}
	if !IsNil(o.ResourceGroup) {
		toSerialize["resource_group"] = o.ResourceGroup
	}
	if !IsNil(o.InstanceTag) {
		toSerialize["instance_tag"] = o.InstanceTag
	}
	return toSerialize, nil
}

func (o *InstanceDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"create_time",
		"update_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceDetail := _InstanceDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceDetail)

	if err != nil {
		return err
	}

	*o = InstanceDetail(varInstanceDetail)

	return err
}

type NullableInstanceDetail struct {
	value *InstanceDetail
	isSet bool
}

func (v NullableInstanceDetail) Get() *InstanceDetail {
	return v.value
}

func (v *NullableInstanceDetail) Set(val *InstanceDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceDetail(val *InstanceDetail) *NullableInstanceDetail {
	return &NullableInstanceDetail{value: val, isSet: true}
}

func (v NullableInstanceDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


