/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExecuteCheck type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecuteCheck{}

// ExecuteCheck struct for ExecuteCheck
type ExecuteCheck struct {
	InstanceId int32 `json:"instance_id"`
	DbName string `json:"db_name"`
	FullSql string `json:"full_sql"`
}

type _ExecuteCheck ExecuteCheck

// NewExecuteCheck instantiates a new ExecuteCheck object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecuteCheck(instanceId int32, dbName string, fullSql string) *ExecuteCheck {
	this := ExecuteCheck{}
	this.InstanceId = instanceId
	this.DbName = dbName
	this.FullSql = fullSql
	return &this
}

// NewExecuteCheckWithDefaults instantiates a new ExecuteCheck object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecuteCheckWithDefaults() *ExecuteCheck {
	this := ExecuteCheck{}
	return &this
}

// GetInstanceId returns the InstanceId field value
func (o *ExecuteCheck) GetInstanceId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value
// and a boolean to check if the value has been set.
func (o *ExecuteCheck) GetInstanceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceId, true
}

// SetInstanceId sets field value
func (o *ExecuteCheck) SetInstanceId(v int32) {
	o.InstanceId = v
}

// GetDbName returns the DbName field value
func (o *ExecuteCheck) GetDbName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DbName
}

// GetDbNameOk returns a tuple with the DbName field value
// and a boolean to check if the value has been set.
func (o *ExecuteCheck) GetDbNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DbName, true
}

// SetDbName sets field value
func (o *ExecuteCheck) SetDbName(v string) {
	o.DbName = v
}

// GetFullSql returns the FullSql field value
func (o *ExecuteCheck) GetFullSql() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullSql
}

// GetFullSqlOk returns a tuple with the FullSql field value
// and a boolean to check if the value has been set.
func (o *ExecuteCheck) GetFullSqlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullSql, true
}

// SetFullSql sets field value
func (o *ExecuteCheck) SetFullSql(v string) {
	o.FullSql = v
}

func (o ExecuteCheck) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecuteCheck) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instance_id"] = o.InstanceId
	toSerialize["db_name"] = o.DbName
	toSerialize["full_sql"] = o.FullSql
	return toSerialize, nil
}

func (o *ExecuteCheck) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instance_id",
		"db_name",
		"full_sql",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExecuteCheck := _ExecuteCheck{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExecuteCheck)

	if err != nil {
		return err
	}

	*o = ExecuteCheck(varExecuteCheck)

	return err
}

type NullableExecuteCheck struct {
	value *ExecuteCheck
	isSet bool
}

func (v NullableExecuteCheck) Get() *ExecuteCheck {
	return v.value
}

func (v *NullableExecuteCheck) Set(val *ExecuteCheck) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteCheck) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteCheck) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteCheck(val *ExecuteCheck) *NullableExecuteCheck {
	return &NullableExecuteCheck{value: val, isSet: true}
}

func (v NullableExecuteCheck) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteCheck) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


