/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserAuth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserAuth{}

// UserAuth struct for UserAuth
type UserAuth struct {
	Engineer string `json:"engineer"`
	Password string `json:"password"`
}

type _UserAuth UserAuth

// NewUserAuth instantiates a new UserAuth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserAuth(engineer string, password string) *UserAuth {
	this := UserAuth{}
	this.Engineer = engineer
	this.Password = password
	return &this
}

// NewUserAuthWithDefaults instantiates a new UserAuth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserAuthWithDefaults() *UserAuth {
	this := UserAuth{}
	return &this
}

// GetEngineer returns the Engineer field value
func (o *UserAuth) GetEngineer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Engineer
}

// GetEngineerOk returns a tuple with the Engineer field value
// and a boolean to check if the value has been set.
func (o *UserAuth) GetEngineerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engineer, true
}

// SetEngineer sets field value
func (o *UserAuth) SetEngineer(v string) {
	o.Engineer = v
}

// GetPassword returns the Password field value
func (o *UserAuth) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *UserAuth) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *UserAuth) SetPassword(v string) {
	o.Password = v
}

func (o UserAuth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserAuth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["engineer"] = o.Engineer
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *UserAuth) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"engineer",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserAuth := _UserAuth{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserAuth)

	if err != nil {
		return err
	}

	*o = UserAuth(varUserAuth)

	return err
}

type NullableUserAuth struct {
	value *UserAuth
	isSet bool
}

func (v NullableUserAuth) Get() *UserAuth {
	return v.value
}

func (v *NullableUserAuth) Set(val *UserAuth) {
	v.value = val
	v.isSet = true
}

func (v NullableUserAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableUserAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserAuth(val *UserAuth) *NullableUserAuth {
	return &NullableUserAuth{value: val, isSet: true}
}

func (v NullableUserAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


