/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LocatorFailureReason type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocatorFailureReason{}

// LocatorFailureReason struct for LocatorFailureReason
type LocatorFailureReason struct {
	InstanceName string `json:"instance_name"`
	Reason string `json:"reason"`
}

type _LocatorFailureReason LocatorFailureReason

// NewLocatorFailureReason instantiates a new LocatorFailureReason object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocatorFailureReason(instanceName string, reason string) *LocatorFailureReason {
	this := LocatorFailureReason{}
	this.InstanceName = instanceName
	this.Reason = reason
	return &this
}

// NewLocatorFailureReasonWithDefaults instantiates a new LocatorFailureReason object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocatorFailureReasonWithDefaults() *LocatorFailureReason {
	this := LocatorFailureReason{}
	return &this
}

// GetInstanceName returns the InstanceName field value
func (o *LocatorFailureReason) GetInstanceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceName
}

// GetInstanceNameOk returns a tuple with the InstanceName field value
// and a boolean to check if the value has been set.
func (o *LocatorFailureReason) GetInstanceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceName, true
}

// SetInstanceName sets field value
func (o *LocatorFailureReason) SetInstanceName(v string) {
	o.InstanceName = v
}

// GetReason returns the Reason field value
func (o *LocatorFailureReason) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *LocatorFailureReason) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *LocatorFailureReason) SetReason(v string) {
	o.Reason = v
}

func (o LocatorFailureReason) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocatorFailureReason) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instance_name"] = o.InstanceName
	toSerialize["reason"] = o.Reason
	return toSerialize, nil
}

func (o *LocatorFailureReason) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instance_name",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLocatorFailureReason := _LocatorFailureReason{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLocatorFailureReason)

	if err != nil {
		return err
	}

	*o = LocatorFailureReason(varLocatorFailureReason)

	return err
}

type NullableLocatorFailureReason struct {
	value *LocatorFailureReason
	isSet bool
}

func (v NullableLocatorFailureReason) Get() *LocatorFailureReason {
	return v.value
}

func (v *NullableLocatorFailureReason) Set(val *LocatorFailureReason) {
	v.value = val
	v.isSet = true
}

func (v NullableLocatorFailureReason) IsSet() bool {
	return v.isSet
}

func (v *NullableLocatorFailureReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocatorFailureReason(val *LocatorFailureReason) *NullableLocatorFailureReason {
	return &NullableLocatorFailureReason{value: val, isSet: true}
}

func (v NullableLocatorFailureReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocatorFailureReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


