/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TableInstanceLookupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableInstanceLookupResponse{}

// TableInstanceLookupResponse struct for TableInstanceLookupResponse
type TableInstanceLookupResponse struct {
	Status int32 `json:"status"`
	Msg string `json:"msg"`
	Count int32 `json:"count"`
	Data []TableInstance `json:"data"`
	Summary NullableLocatorExecutionSummary `json:"summary,omitempty"`
}

type _TableInstanceLookupResponse TableInstanceLookupResponse

// NewTableInstanceLookupResponse instantiates a new TableInstanceLookupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableInstanceLookupResponse(status int32, msg string, count int32, data []TableInstance) *TableInstanceLookupResponse {
	this := TableInstanceLookupResponse{}
	this.Status = status
	this.Msg = msg
	this.Count = count
	this.Data = data
	return &this
}

// NewTableInstanceLookupResponseWithDefaults instantiates a new TableInstanceLookupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableInstanceLookupResponseWithDefaults() *TableInstanceLookupResponse {
	this := TableInstanceLookupResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *TableInstanceLookupResponse) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TableInstanceLookupResponse) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TableInstanceLookupResponse) SetStatus(v int32) {
	o.Status = v
}

// GetMsg returns the Msg field value
func (o *TableInstanceLookupResponse) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *TableInstanceLookupResponse) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *TableInstanceLookupResponse) SetMsg(v string) {
	o.Msg = v
}

// GetCount returns the Count field value
func (o *TableInstanceLookupResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *TableInstanceLookupResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *TableInstanceLookupResponse) SetCount(v int32) {
	o.Count = v
}

// GetData returns the Data field value
func (o *TableInstanceLookupResponse) GetData() []TableInstance {
	if o == nil {
		var ret []TableInstance
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TableInstanceLookupResponse) GetDataOk() ([]TableInstance, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *TableInstanceLookupResponse) SetData(v []TableInstance) {
	o.Data = v
}

// GetSummary returns the Summary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TableInstanceLookupResponse) GetSummary() LocatorExecutionSummary {
	if o == nil || IsNil(o.Summary.Get()) {
		var ret LocatorExecutionSummary
		return ret
	}
	return *o.Summary.Get()
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TableInstanceLookupResponse) GetSummaryOk() (*LocatorExecutionSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Summary.Get(), o.Summary.IsSet()
}

// HasSummary returns a boolean if a field has been set.
func (o *TableInstanceLookupResponse) HasSummary() bool {
	if o != nil && o.Summary.IsSet() {
		return true
	}

	return false
}

// SetSummary gets a reference to the given NullableLocatorExecutionSummary and assigns it to the Summary field.
func (o *TableInstanceLookupResponse) SetSummary(v LocatorExecutionSummary) {
	o.Summary.Set(&v)
}
// SetSummaryNil sets the value for Summary to be an explicit nil
func (o *TableInstanceLookupResponse) SetSummaryNil() {
	o.Summary.Set(nil)
}

// UnsetSummary ensures that no value is present for Summary, not even an explicit nil
func (o *TableInstanceLookupResponse) UnsetSummary() {
	o.Summary.Unset()
}

func (o TableInstanceLookupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableInstanceLookupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["msg"] = o.Msg
	toSerialize["count"] = o.Count
	toSerialize["data"] = o.Data
	if o.Summary.IsSet() {
		toSerialize["summary"] = o.Summary.Get()
	}
	return toSerialize, nil
}

func (o *TableInstanceLookupResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"msg",
		"count",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTableInstanceLookupResponse := _TableInstanceLookupResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTableInstanceLookupResponse)

	if err != nil {
		return err
	}

	*o = TableInstanceLookupResponse(varTableInstanceLookupResponse)

	return err
}

type NullableTableInstanceLookupResponse struct {
	value *TableInstanceLookupResponse
	isSet bool
}

func (v NullableTableInstanceLookupResponse) Get() *TableInstanceLookupResponse {
	return v.value
}

func (v *NullableTableInstanceLookupResponse) Set(val *TableInstanceLookupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTableInstanceLookupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTableInstanceLookupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableInstanceLookupResponse(val *TableInstanceLookupResponse) *NullableTableInstanceLookupResponse {
	return &NullableTableInstanceLookupResponse{value: val, isSet: true}
}

func (v NullableTableInstanceLookupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableInstanceLookupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


