/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// StatusEnum * `workflow_finish` - 已正常结束 * `workflow_abort` - 人工终止流程 * `workflow_manreviewing` - 等待审核人审核 * `workflow_review_pass` - 审核通过 * `workflow_timingtask` - 定时执行 * `workflow_queuing` - 排队中 * `workflow_executing` - 执行中 * `workflow_autoreviewwrong` - 自动审核不通过 * `workflow_exception` - 执行有异常
type StatusEnum string

// List of StatusEnum
const (
	STATUSENUM_WORKFLOW_FINISH StatusEnum = "workflow_finish"
	STATUSENUM_WORKFLOW_ABORT StatusEnum = "workflow_abort"
	STATUSENUM_WORKFLOW_MANREVIEWING StatusEnum = "workflow_manreviewing"
	STATUSENUM_WORKFLOW_REVIEW_PASS StatusEnum = "workflow_review_pass"
	STATUSENUM_WORKFLOW_TIMINGTASK StatusEnum = "workflow_timingtask"
	STATUSENUM_WORKFLOW_QUEUING StatusEnum = "workflow_queuing"
	STATUSENUM_WORKFLOW_EXECUTING StatusEnum = "workflow_executing"
	STATUSENUM_WORKFLOW_AUTOREVIEWWRONG StatusEnum = "workflow_autoreviewwrong"
	STATUSENUM_WORKFLOW_EXCEPTION StatusEnum = "workflow_exception"
)

// All allowed values of StatusEnum enum
var AllowedStatusEnumEnumValues = []StatusEnum{
	"workflow_finish",
	"workflow_abort",
	"workflow_manreviewing",
	"workflow_review_pass",
	"workflow_timingtask",
	"workflow_queuing",
	"workflow_executing",
	"workflow_autoreviewwrong",
	"workflow_exception",
}

func (v *StatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := StatusEnum(value)
	for _, existing := range AllowedStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid StatusEnum", value)
}

// NewStatusEnumFromValue returns a pointer to a valid StatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatusEnumFromValue(v string) (*StatusEnum, error) {
	ev := StatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for StatusEnum: valid values are %v", v, AllowedStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v StatusEnum) IsValid() bool {
	for _, existing := range AllowedStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to StatusEnum value
func (v StatusEnum) Ptr() *StatusEnum {
	return &v
}

type NullableStatusEnum struct {
	value *StatusEnum
	isSet bool
}

func (v NullableStatusEnum) Get() *StatusEnum {
	return v.value
}

func (v *NullableStatusEnum) Set(val *StatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusEnum(val *StatusEnum) *NullableStatusEnum {
	return &NullableStatusEnum{value: val, isSet: true}
}

func (v NullableStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

