/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ExportFormatEnum * `csv` - CSV * `xlsx` - Excel * `sql` - SQL * `json` - JSON * `xml` - XML
type ExportFormatEnum string

// List of ExportFormatEnum
const (
	EXPORTFORMATENUM_CSV ExportFormatEnum = "csv"
	EXPORTFORMATENUM_XLSX ExportFormatEnum = "xlsx"
	EXPORTFORMATENUM_SQL ExportFormatEnum = "sql"
	EXPORTFORMATENUM_JSON ExportFormatEnum = "json"
	EXPORTFORMATENUM_XML ExportFormatEnum = "xml"
)

// All allowed values of ExportFormatEnum enum
var AllowedExportFormatEnumEnumValues = []ExportFormatEnum{
	"csv",
	"xlsx",
	"sql",
	"json",
	"xml",
}

func (v *ExportFormatEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ExportFormatEnum(value)
	for _, existing := range AllowedExportFormatEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ExportFormatEnum", value)
}

// NewExportFormatEnumFromValue returns a pointer to a valid ExportFormatEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewExportFormatEnumFromValue(v string) (*ExportFormatEnum, error) {
	ev := ExportFormatEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ExportFormatEnum: valid values are %v", v, AllowedExportFormatEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ExportFormatEnum) IsValid() bool {
	for _, existing := range AllowedExportFormatEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ExportFormatEnum value
func (v ExportFormatEnum) Ptr() *ExportFormatEnum {
	return &v
}

type NullableExportFormatEnum struct {
	value *ExportFormatEnum
	isSet bool
}

func (v NullableExportFormatEnum) Get() *ExportFormatEnum {
	return v.value
}

func (v *NullableExportFormatEnum) Set(val *ExportFormatEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableExportFormatEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableExportFormatEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportFormatEnum(val *ExportFormatEnum) *NullableExportFormatEnum {
	return &NullableExportFormatEnum{value: val, isSet: true}
}

func (v NullableExportFormatEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportFormatEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

