/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WorkflowLogList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowLogList{}

// WorkflowLogList struct for WorkflowLogList
type WorkflowLogList struct {
	OperationTypeDesc string `json:"operation_type_desc"`
	OperationInfo string `json:"operation_info"`
	OperatorDisplay *string `json:"operator_display,omitempty"`
	OperationTime time.Time `json:"operation_time"`
}

type _WorkflowLogList WorkflowLogList

// NewWorkflowLogList instantiates a new WorkflowLogList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowLogList(operationTypeDesc string, operationInfo string, operationTime time.Time) *WorkflowLogList {
	this := WorkflowLogList{}
	this.OperationTypeDesc = operationTypeDesc
	this.OperationInfo = operationInfo
	this.OperationTime = operationTime
	return &this
}

// NewWorkflowLogListWithDefaults instantiates a new WorkflowLogList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowLogListWithDefaults() *WorkflowLogList {
	this := WorkflowLogList{}
	return &this
}

// GetOperationTypeDesc returns the OperationTypeDesc field value
func (o *WorkflowLogList) GetOperationTypeDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationTypeDesc
}

// GetOperationTypeDescOk returns a tuple with the OperationTypeDesc field value
// and a boolean to check if the value has been set.
func (o *WorkflowLogList) GetOperationTypeDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationTypeDesc, true
}

// SetOperationTypeDesc sets field value
func (o *WorkflowLogList) SetOperationTypeDesc(v string) {
	o.OperationTypeDesc = v
}

// GetOperationInfo returns the OperationInfo field value
func (o *WorkflowLogList) GetOperationInfo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationInfo
}

// GetOperationInfoOk returns a tuple with the OperationInfo field value
// and a boolean to check if the value has been set.
func (o *WorkflowLogList) GetOperationInfoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationInfo, true
}

// SetOperationInfo sets field value
func (o *WorkflowLogList) SetOperationInfo(v string) {
	o.OperationInfo = v
}

// GetOperatorDisplay returns the OperatorDisplay field value if set, zero value otherwise.
func (o *WorkflowLogList) GetOperatorDisplay() string {
	if o == nil || IsNil(o.OperatorDisplay) {
		var ret string
		return ret
	}
	return *o.OperatorDisplay
}

// GetOperatorDisplayOk returns a tuple with the OperatorDisplay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowLogList) GetOperatorDisplayOk() (*string, bool) {
	if o == nil || IsNil(o.OperatorDisplay) {
		return nil, false
	}
	return o.OperatorDisplay, true
}

// HasOperatorDisplay returns a boolean if a field has been set.
func (o *WorkflowLogList) HasOperatorDisplay() bool {
	if o != nil && !IsNil(o.OperatorDisplay) {
		return true
	}

	return false
}

// SetOperatorDisplay gets a reference to the given string and assigns it to the OperatorDisplay field.
func (o *WorkflowLogList) SetOperatorDisplay(v string) {
	o.OperatorDisplay = &v
}

// GetOperationTime returns the OperationTime field value
func (o *WorkflowLogList) GetOperationTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.OperationTime
}

// GetOperationTimeOk returns a tuple with the OperationTime field value
// and a boolean to check if the value has been set.
func (o *WorkflowLogList) GetOperationTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationTime, true
}

// SetOperationTime sets field value
func (o *WorkflowLogList) SetOperationTime(v time.Time) {
	o.OperationTime = v
}

func (o WorkflowLogList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowLogList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operation_type_desc"] = o.OperationTypeDesc
	toSerialize["operation_info"] = o.OperationInfo
	if !IsNil(o.OperatorDisplay) {
		toSerialize["operator_display"] = o.OperatorDisplay
	}
	toSerialize["operation_time"] = o.OperationTime
	return toSerialize, nil
}

func (o *WorkflowLogList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operation_type_desc",
		"operation_info",
		"operation_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowLogList := _WorkflowLogList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowLogList)

	if err != nil {
		return err
	}

	*o = WorkflowLogList(varWorkflowLogList)

	return err
}

type NullableWorkflowLogList struct {
	value *WorkflowLogList
	isSet bool
}

func (v NullableWorkflowLogList) Get() *WorkflowLogList {
	return v.value
}

func (v *NullableWorkflowLogList) Set(val *WorkflowLogList) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowLogList) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowLogList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowLogList(val *WorkflowLogList) *NullableWorkflowLogList {
	return &NullableWorkflowLogList{value: val, isSet: true}
}

func (v NullableWorkflowLogList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowLogList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


