/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TwoFAVerify type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TwoFAVerify{}

// TwoFAVerify struct for TwoFAVerify
type TwoFAVerify struct {
	Engineer string `json:"engineer"`
	Otp int32 `json:"otp"`
	Key *string `json:"key,omitempty"`
	Phone *string `json:"phone,omitempty"`
	AuthType string `json:"auth_type"`
}

type _TwoFAVerify TwoFAVerify

// NewTwoFAVerify instantiates a new TwoFAVerify object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTwoFAVerify(engineer string, otp int32, authType string) *TwoFAVerify {
	this := TwoFAVerify{}
	this.Engineer = engineer
	this.Otp = otp
	this.AuthType = authType
	return &this
}

// NewTwoFAVerifyWithDefaults instantiates a new TwoFAVerify object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTwoFAVerifyWithDefaults() *TwoFAVerify {
	this := TwoFAVerify{}
	return &this
}

// GetEngineer returns the Engineer field value
func (o *TwoFAVerify) GetEngineer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Engineer
}

// GetEngineerOk returns a tuple with the Engineer field value
// and a boolean to check if the value has been set.
func (o *TwoFAVerify) GetEngineerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engineer, true
}

// SetEngineer sets field value
func (o *TwoFAVerify) SetEngineer(v string) {
	o.Engineer = v
}

// GetOtp returns the Otp field value
func (o *TwoFAVerify) GetOtp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Otp
}

// GetOtpOk returns a tuple with the Otp field value
// and a boolean to check if the value has been set.
func (o *TwoFAVerify) GetOtpOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Otp, true
}

// SetOtp sets field value
func (o *TwoFAVerify) SetOtp(v int32) {
	o.Otp = v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *TwoFAVerify) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFAVerify) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *TwoFAVerify) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *TwoFAVerify) SetKey(v string) {
	o.Key = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *TwoFAVerify) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFAVerify) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *TwoFAVerify) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *TwoFAVerify) SetPhone(v string) {
	o.Phone = &v
}

// GetAuthType returns the AuthType field value
func (o *TwoFAVerify) GetAuthType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *TwoFAVerify) GetAuthTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *TwoFAVerify) SetAuthType(v string) {
	o.AuthType = v
}

func (o TwoFAVerify) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TwoFAVerify) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["engineer"] = o.Engineer
	toSerialize["otp"] = o.Otp
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	toSerialize["auth_type"] = o.AuthType
	return toSerialize, nil
}

func (o *TwoFAVerify) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"engineer",
		"otp",
		"auth_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTwoFAVerify := _TwoFAVerify{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTwoFAVerify)

	if err != nil {
		return err
	}

	*o = TwoFAVerify(varTwoFAVerify)

	return err
}

type NullableTwoFAVerify struct {
	value *TwoFAVerify
	isSet bool
}

func (v NullableTwoFAVerify) Get() *TwoFAVerify {
	return v.value
}

func (v *NullableTwoFAVerify) Set(val *TwoFAVerify) {
	v.value = val
	v.isSet = true
}

func (v NullableTwoFAVerify) IsSet() bool {
	return v.isSet
}

func (v *NullableTwoFAVerify) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwoFAVerify(val *TwoFAVerify) *NullableTwoFAVerify {
	return &NullableTwoFAVerify{value: val, isSet: true}
}

func (v NullableTwoFAVerify) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwoFAVerify) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


