/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// AuditTypeEnum * `pass` - pass * `cancel` - cancel
type AuditTypeEnum string

// List of AuditTypeEnum
const (
	AUDITTYPEENUM_PASS AuditTypeEnum = "pass"
	AUDITTYPEENUM_CANCEL AuditTypeEnum = "cancel"
)

// All allowed values of AuditTypeEnum enum
var AllowedAuditTypeEnumEnumValues = []AuditTypeEnum{
	"pass",
	"cancel",
}

func (v *AuditTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AuditTypeEnum(value)
	for _, existing := range AllowedAuditTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AuditTypeEnum", value)
}

// NewAuditTypeEnumFromValue returns a pointer to a valid AuditTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAuditTypeEnumFromValue(v string) (*AuditTypeEnum, error) {
	ev := AuditTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AuditTypeEnum: valid values are %v", v, AllowedAuditTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AuditTypeEnum) IsValid() bool {
	for _, existing := range AllowedAuditTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AuditTypeEnum value
func (v AuditTypeEnum) Ptr() *AuditTypeEnum {
	return &v
}

type NullableAuditTypeEnum struct {
	value *AuditTypeEnum
	isSet bool
}

func (v NullableAuditTypeEnum) Get() *AuditTypeEnum {
	return v.value
}

func (v *NullableAuditTypeEnum) Set(val *AuditTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditTypeEnum(val *AuditTypeEnum) *NullableAuditTypeEnum {
	return &NullableAuditTypeEnum{value: val, isSet: true}
}

func (v NullableAuditTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

