/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TwoFAAuthTypeEnum * `totp` - totp * `sms` - sms
type TwoFAAuthTypeEnum string

// List of TwoFAAuthTypeEnum
const (
	TWOFAAUTHTYPEENUM_TOTP TwoFAAuthTypeEnum = "totp"
	TWOFAAUTHTYPEENUM_SMS TwoFAAuthTypeEnum = "sms"
)

// All allowed values of TwoFAAuthTypeEnum enum
var AllowedTwoFAAuthTypeEnumEnumValues = []TwoFAAuthTypeEnum{
	"totp",
	"sms",
}

func (v *TwoFAAuthTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TwoFAAuthTypeEnum(value)
	for _, existing := range AllowedTwoFAAuthTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TwoFAAuthTypeEnum", value)
}

// NewTwoFAAuthTypeEnumFromValue returns a pointer to a valid TwoFAAuthTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTwoFAAuthTypeEnumFromValue(v string) (*TwoFAAuthTypeEnum, error) {
	ev := TwoFAAuthTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TwoFAAuthTypeEnum: valid values are %v", v, AllowedTwoFAAuthTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TwoFAAuthTypeEnum) IsValid() bool {
	for _, existing := range AllowedTwoFAAuthTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TwoFAAuthTypeEnum value
func (v TwoFAAuthTypeEnum) Ptr() *TwoFAAuthTypeEnum {
	return &v
}

type NullableTwoFAAuthTypeEnum struct {
	value *TwoFAAuthTypeEnum
	isSet bool
}

func (v NullableTwoFAAuthTypeEnum) Get() *TwoFAAuthTypeEnum {
	return v.value
}

func (v *NullableTwoFAAuthTypeEnum) Set(val *TwoFAAuthTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableTwoFAAuthTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableTwoFAAuthTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwoFAAuthTypeEnum(val *TwoFAAuthTypeEnum) *NullableTwoFAAuthTypeEnum {
	return &NullableTwoFAAuthTypeEnum{value: val, isSet: true}
}

func (v NullableTwoFAAuthTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwoFAAuthTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

