/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ModeDf2Enum * `standalone` - 单机 * `cluster` - 集群
type ModeDf2Enum string

// List of ModeDf2Enum
const (
	MODEDF2ENUM_STANDALONE ModeDf2Enum = "standalone"
	MODEDF2ENUM_CLUSTER ModeDf2Enum = "cluster"
)

// All allowed values of ModeDf2Enum enum
var AllowedModeDf2EnumEnumValues = []ModeDf2Enum{
	"standalone",
	"cluster",
}

func (v *ModeDf2Enum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ModeDf2Enum(value)
	for _, existing := range AllowedModeDf2EnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ModeDf2Enum", value)
}

// NewModeDf2EnumFromValue returns a pointer to a valid ModeDf2Enum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewModeDf2EnumFromValue(v string) (*ModeDf2Enum, error) {
	ev := ModeDf2Enum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ModeDf2Enum: valid values are %v", v, AllowedModeDf2EnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ModeDf2Enum) IsValid() bool {
	for _, existing := range AllowedModeDf2EnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ModeDf2Enum value
func (v ModeDf2Enum) Ptr() *ModeDf2Enum {
	return &v
}

type NullableModeDf2Enum struct {
	value *ModeDf2Enum
	isSet bool
}

func (v NullableModeDf2Enum) Get() *ModeDf2Enum {
	return v.value
}

func (v *NullableModeDf2Enum) Set(val *ModeDf2Enum) {
	v.value = val
	v.isSet = true
}

func (v NullableModeDf2Enum) IsSet() bool {
	return v.isSet
}

func (v *NullableModeDf2Enum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModeDf2Enum(val *ModeDf2Enum) *NullableModeDf2Enum {
	return &NullableModeDf2Enum{value: val, isSet: true}
}

func (v NullableModeDf2Enum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModeDf2Enum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

