/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AliyunRds type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AliyunRds{}

// AliyunRds struct for AliyunRds
type AliyunRds struct {
	Id int32 `json:"id"`
	RdsDbinstanceid string `json:"rds_dbinstanceid"`
	IsEnable *bool `json:"is_enable,omitempty"`
	Instance int32 `json:"instance"`
	Ak CloudAccessKey `json:"ak"`
}

type _AliyunRds AliyunRds

// NewAliyunRds instantiates a new AliyunRds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAliyunRds(id int32, rdsDbinstanceid string, instance int32, ak CloudAccessKey) *AliyunRds {
	this := AliyunRds{}
	this.Id = id
	this.RdsDbinstanceid = rdsDbinstanceid
	this.Instance = instance
	this.Ak = ak
	return &this
}

// NewAliyunRdsWithDefaults instantiates a new AliyunRds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAliyunRdsWithDefaults() *AliyunRds {
	this := AliyunRds{}
	return &this
}

// GetId returns the Id field value
func (o *AliyunRds) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AliyunRds) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AliyunRds) SetId(v int32) {
	o.Id = v
}

// GetRdsDbinstanceid returns the RdsDbinstanceid field value
func (o *AliyunRds) GetRdsDbinstanceid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RdsDbinstanceid
}

// GetRdsDbinstanceidOk returns a tuple with the RdsDbinstanceid field value
// and a boolean to check if the value has been set.
func (o *AliyunRds) GetRdsDbinstanceidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RdsDbinstanceid, true
}

// SetRdsDbinstanceid sets field value
func (o *AliyunRds) SetRdsDbinstanceid(v string) {
	o.RdsDbinstanceid = v
}

// GetIsEnable returns the IsEnable field value if set, zero value otherwise.
func (o *AliyunRds) GetIsEnable() bool {
	if o == nil || IsNil(o.IsEnable) {
		var ret bool
		return ret
	}
	return *o.IsEnable
}

// GetIsEnableOk returns a tuple with the IsEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AliyunRds) GetIsEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnable) {
		return nil, false
	}
	return o.IsEnable, true
}

// HasIsEnable returns a boolean if a field has been set.
func (o *AliyunRds) HasIsEnable() bool {
	if o != nil && !IsNil(o.IsEnable) {
		return true
	}

	return false
}

// SetIsEnable gets a reference to the given bool and assigns it to the IsEnable field.
func (o *AliyunRds) SetIsEnable(v bool) {
	o.IsEnable = &v
}

// GetInstance returns the Instance field value
func (o *AliyunRds) GetInstance() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value
// and a boolean to check if the value has been set.
func (o *AliyunRds) GetInstanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instance, true
}

// SetInstance sets field value
func (o *AliyunRds) SetInstance(v int32) {
	o.Instance = v
}

// GetAk returns the Ak field value
func (o *AliyunRds) GetAk() CloudAccessKey {
	if o == nil {
		var ret CloudAccessKey
		return ret
	}

	return o.Ak
}

// GetAkOk returns a tuple with the Ak field value
// and a boolean to check if the value has been set.
func (o *AliyunRds) GetAkOk() (*CloudAccessKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ak, true
}

// SetAk sets field value
func (o *AliyunRds) SetAk(v CloudAccessKey) {
	o.Ak = v
}

func (o AliyunRds) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AliyunRds) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["rds_dbinstanceid"] = o.RdsDbinstanceid
	if !IsNil(o.IsEnable) {
		toSerialize["is_enable"] = o.IsEnable
	}
	toSerialize["instance"] = o.Instance
	toSerialize["ak"] = o.Ak
	return toSerialize, nil
}

func (o *AliyunRds) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"rds_dbinstanceid",
		"instance",
		"ak",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAliyunRds := _AliyunRds{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAliyunRds)

	if err != nil {
		return err
	}

	*o = AliyunRds(varAliyunRds)

	return err
}

type NullableAliyunRds struct {
	value *AliyunRds
	isSet bool
}

func (v NullableAliyunRds) Get() *AliyunRds {
	return v.value
}

func (v *NullableAliyunRds) Set(val *AliyunRds) {
	v.value = val
	v.isSet = true
}

func (v NullableAliyunRds) IsSet() bool {
	return v.isSet
}

func (v *NullableAliyunRds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAliyunRds(val *AliyunRds) *NullableAliyunRds {
	return &NullableAliyunRds{value: val, isSet: true}
}

func (v NullableAliyunRds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAliyunRds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


