/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CloudAccessKeyTypeEnum * `aliyun` - aliyun
type CloudAccessKeyTypeEnum string

// List of CloudAccessKeyTypeEnum
const (
	CLOUDACCESSKEYTYPEENUM_ALIYUN CloudAccessKeyTypeEnum = "aliyun"
)

// All allowed values of CloudAccessKeyTypeEnum enum
var AllowedCloudAccessKeyTypeEnumEnumValues = []CloudAccessKeyTypeEnum{
	"aliyun",
}

func (v *CloudAccessKeyTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CloudAccessKeyTypeEnum(value)
	for _, existing := range AllowedCloudAccessKeyTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CloudAccessKeyTypeEnum", value)
}

// NewCloudAccessKeyTypeEnumFromValue returns a pointer to a valid CloudAccessKeyTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCloudAccessKeyTypeEnumFromValue(v string) (*CloudAccessKeyTypeEnum, error) {
	ev := CloudAccessKeyTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CloudAccessKeyTypeEnum: valid values are %v", v, AllowedCloudAccessKeyTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CloudAccessKeyTypeEnum) IsValid() bool {
	for _, existing := range AllowedCloudAccessKeyTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CloudAccessKeyTypeEnum value
func (v CloudAccessKeyTypeEnum) Ptr() *CloudAccessKeyTypeEnum {
	return &v
}

type NullableCloudAccessKeyTypeEnum struct {
	value *CloudAccessKeyTypeEnum
	isSet bool
}

func (v NullableCloudAccessKeyTypeEnum) Get() *CloudAccessKeyTypeEnum {
	return v.value
}

func (v *NullableCloudAccessKeyTypeEnum) Set(val *CloudAccessKeyTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudAccessKeyTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudAccessKeyTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudAccessKeyTypeEnum(val *CloudAccessKeyTypeEnum) *NullableCloudAccessKeyTypeEnum {
	return &NullableCloudAccessKeyTypeEnum{value: val, isSet: true}
}

func (v NullableCloudAccessKeyTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudAccessKeyTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

