/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CurrentStatusEnum * `0` - 待审核 * `1` - 审核通过 * `2` - 审核不通过 * `3` - 审核取消
type CurrentStatusEnum int32

// List of CurrentStatusEnum
const (
	CURRENTSTATUSENUM__0 CurrentStatusEnum = 0
	CURRENTSTATUSENUM__1 CurrentStatusEnum = 1
	CURRENTSTATUSENUM__2 CurrentStatusEnum = 2
	CURRENTSTATUSENUM__3 CurrentStatusEnum = 3
)

// All allowed values of CurrentStatusEnum enum
var AllowedCurrentStatusEnumEnumValues = []CurrentStatusEnum{
	0,
	1,
	2,
	3,
}

func (v *CurrentStatusEnum) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CurrentStatusEnum(value)
	for _, existing := range AllowedCurrentStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CurrentStatusEnum", value)
}

// NewCurrentStatusEnumFromValue returns a pointer to a valid CurrentStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCurrentStatusEnumFromValue(v int32) (*CurrentStatusEnum, error) {
	ev := CurrentStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CurrentStatusEnum: valid values are %v", v, AllowedCurrentStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CurrentStatusEnum) IsValid() bool {
	for _, existing := range AllowedCurrentStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CurrentStatusEnum value
func (v CurrentStatusEnum) Ptr() *CurrentStatusEnum {
	return &v
}

type NullableCurrentStatusEnum struct {
	value *CurrentStatusEnum
	isSet bool
}

func (v NullableCurrentStatusEnum) Get() *CurrentStatusEnum {
	return v.value
}

func (v *NullableCurrentStatusEnum) Set(val *CurrentStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCurrentStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCurrentStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurrentStatusEnum(val *CurrentStatusEnum) *NullableCurrentStatusEnum {
	return &NullableCurrentStatusEnum{value: val, isSet: true}
}

func (v NullableCurrentStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurrentStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

