/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TwoFASaveAuthTypeEnum * `disabled` - disabled * `totp` - totp * `sms` - sms
type TwoFASaveAuthTypeEnum string

// List of TwoFASaveAuthTypeEnum
const (
	TWOFASAVEAUTHTYPEENUM_DISABLED TwoFASaveAuthTypeEnum = "disabled"
	TWOFASAVEAUTHTYPEENUM_TOTP TwoFASaveAuthTypeEnum = "totp"
	TWOFASAVEAUTHTYPEENUM_SMS TwoFASaveAuthTypeEnum = "sms"
)

// All allowed values of TwoFASaveAuthTypeEnum enum
var AllowedTwoFASaveAuthTypeEnumEnumValues = []TwoFASaveAuthTypeEnum{
	"disabled",
	"totp",
	"sms",
}

func (v *TwoFASaveAuthTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TwoFASaveAuthTypeEnum(value)
	for _, existing := range AllowedTwoFASaveAuthTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TwoFASaveAuthTypeEnum", value)
}

// NewTwoFASaveAuthTypeEnumFromValue returns a pointer to a valid TwoFASaveAuthTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTwoFASaveAuthTypeEnumFromValue(v string) (*TwoFASaveAuthTypeEnum, error) {
	ev := TwoFASaveAuthTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TwoFASaveAuthTypeEnum: valid values are %v", v, AllowedTwoFASaveAuthTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TwoFASaveAuthTypeEnum) IsValid() bool {
	for _, existing := range AllowedTwoFASaveAuthTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TwoFASaveAuthTypeEnum value
func (v TwoFASaveAuthTypeEnum) Ptr() *TwoFASaveAuthTypeEnum {
	return &v
}

type NullableTwoFASaveAuthTypeEnum struct {
	value *TwoFASaveAuthTypeEnum
	isSet bool
}

func (v NullableTwoFASaveAuthTypeEnum) Get() *TwoFASaveAuthTypeEnum {
	return v.value
}

func (v *NullableTwoFASaveAuthTypeEnum) Set(val *TwoFASaveAuthTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableTwoFASaveAuthTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableTwoFASaveAuthTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwoFASaveAuthTypeEnum(val *TwoFASaveAuthTypeEnum) *NullableTwoFASaveAuthTypeEnum {
	return &NullableTwoFASaveAuthTypeEnum{value: val, isSet: true}
}

func (v NullableTwoFASaveAuthTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwoFASaveAuthTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

