/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// WorkflowTypeA27Enum * `1` - 查询权限申请 * `2` - SQL上线申请 * `3` - 数据归档申请
type WorkflowTypeA27Enum int32

// List of WorkflowTypeA27Enum
const (
	WORKFLOWTYPEA27ENUM__1 WorkflowTypeA27Enum = 1
	WORKFLOWTYPEA27ENUM__2 WorkflowTypeA27Enum = 2
	WORKFLOWTYPEA27ENUM__3 WorkflowTypeA27Enum = 3
)

// All allowed values of WorkflowTypeA27Enum enum
var AllowedWorkflowTypeA27EnumEnumValues = []WorkflowTypeA27Enum{
	1,
	2,
	3,
}

func (v *WorkflowTypeA27Enum) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WorkflowTypeA27Enum(value)
	for _, existing := range AllowedWorkflowTypeA27EnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WorkflowTypeA27Enum", value)
}

// NewWorkflowTypeA27EnumFromValue returns a pointer to a valid WorkflowTypeA27Enum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWorkflowTypeA27EnumFromValue(v int32) (*WorkflowTypeA27Enum, error) {
	ev := WorkflowTypeA27Enum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WorkflowTypeA27Enum: valid values are %v", v, AllowedWorkflowTypeA27EnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WorkflowTypeA27Enum) IsValid() bool {
	for _, existing := range AllowedWorkflowTypeA27EnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WorkflowTypeA27Enum value
func (v WorkflowTypeA27Enum) Ptr() *WorkflowTypeA27Enum {
	return &v
}

type NullableWorkflowTypeA27Enum struct {
	value *WorkflowTypeA27Enum
	isSet bool
}

func (v NullableWorkflowTypeA27Enum) Get() *WorkflowTypeA27Enum {
	return v.value
}

func (v *NullableWorkflowTypeA27Enum) Set(val *WorkflowTypeA27Enum) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowTypeA27Enum) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowTypeA27Enum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowTypeA27Enum(val *WorkflowTypeA27Enum) *NullableWorkflowTypeA27Enum {
	return &NullableWorkflowTypeA27Enum{value: val, isSet: true}
}

func (v NullableWorkflowTypeA27Enum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowTypeA27Enum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

