/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ExecuteWorkflowModeEnum * `auto` - auto * `manual` - manual
type ExecuteWorkflowModeEnum string

// List of ExecuteWorkflowModeEnum
const (
	EXECUTEWORKFLOWMODEENUM_AUTO ExecuteWorkflowModeEnum = "auto"
	EXECUTEWORKFLOWMODEENUM_MANUAL ExecuteWorkflowModeEnum = "manual"
)

// All allowed values of ExecuteWorkflowModeEnum enum
var AllowedExecuteWorkflowModeEnumEnumValues = []ExecuteWorkflowModeEnum{
	"auto",
	"manual",
}

func (v *ExecuteWorkflowModeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ExecuteWorkflowModeEnum(value)
	for _, existing := range AllowedExecuteWorkflowModeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ExecuteWorkflowModeEnum", value)
}

// NewExecuteWorkflowModeEnumFromValue returns a pointer to a valid ExecuteWorkflowModeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewExecuteWorkflowModeEnumFromValue(v string) (*ExecuteWorkflowModeEnum, error) {
	ev := ExecuteWorkflowModeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ExecuteWorkflowModeEnum: valid values are %v", v, AllowedExecuteWorkflowModeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ExecuteWorkflowModeEnum) IsValid() bool {
	for _, existing := range AllowedExecuteWorkflowModeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ExecuteWorkflowModeEnum value
func (v ExecuteWorkflowModeEnum) Ptr() *ExecuteWorkflowModeEnum {
	return &v
}

type NullableExecuteWorkflowModeEnum struct {
	value *ExecuteWorkflowModeEnum
	isSet bool
}

func (v NullableExecuteWorkflowModeEnum) Get() *ExecuteWorkflowModeEnum {
	return v.value
}

func (v *NullableExecuteWorkflowModeEnum) Set(val *ExecuteWorkflowModeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteWorkflowModeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteWorkflowModeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteWorkflowModeEnum(val *ExecuteWorkflowModeEnum) *NullableExecuteWorkflowModeEnum {
	return &NullableExecuteWorkflowModeEnum{value: val, isSet: true}
}

func (v NullableExecuteWorkflowModeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteWorkflowModeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

