/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuditWorkflow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditWorkflow{}

// AuditWorkflow struct for AuditWorkflow
type AuditWorkflow struct {
	Engineer string `json:"engineer"`
	WorkflowId int32 `json:"workflow_id"`
	AuditRemark string `json:"audit_remark"`
	WorkflowType WorkflowTypeA27Enum `json:"workflow_type"`
	AuditType AuditTypeEnum `json:"audit_type"`
}

type _AuditWorkflow AuditWorkflow

// NewAuditWorkflow instantiates a new AuditWorkflow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditWorkflow(engineer string, workflowId int32, auditRemark string, workflowType WorkflowTypeA27Enum, auditType AuditTypeEnum) *AuditWorkflow {
	this := AuditWorkflow{}
	this.Engineer = engineer
	this.WorkflowId = workflowId
	this.AuditRemark = auditRemark
	this.WorkflowType = workflowType
	this.AuditType = auditType
	return &this
}

// NewAuditWorkflowWithDefaults instantiates a new AuditWorkflow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditWorkflowWithDefaults() *AuditWorkflow {
	this := AuditWorkflow{}
	return &this
}

// GetEngineer returns the Engineer field value
func (o *AuditWorkflow) GetEngineer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Engineer
}

// GetEngineerOk returns a tuple with the Engineer field value
// and a boolean to check if the value has been set.
func (o *AuditWorkflow) GetEngineerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engineer, true
}

// SetEngineer sets field value
func (o *AuditWorkflow) SetEngineer(v string) {
	o.Engineer = v
}

// GetWorkflowId returns the WorkflowId field value
func (o *AuditWorkflow) GetWorkflowId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
func (o *AuditWorkflow) GetWorkflowIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowId, true
}

// SetWorkflowId sets field value
func (o *AuditWorkflow) SetWorkflowId(v int32) {
	o.WorkflowId = v
}

// GetAuditRemark returns the AuditRemark field value
func (o *AuditWorkflow) GetAuditRemark() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuditRemark
}

// GetAuditRemarkOk returns a tuple with the AuditRemark field value
// and a boolean to check if the value has been set.
func (o *AuditWorkflow) GetAuditRemarkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditRemark, true
}

// SetAuditRemark sets field value
func (o *AuditWorkflow) SetAuditRemark(v string) {
	o.AuditRemark = v
}

// GetWorkflowType returns the WorkflowType field value
func (o *AuditWorkflow) GetWorkflowType() WorkflowTypeA27Enum {
	if o == nil {
		var ret WorkflowTypeA27Enum
		return ret
	}

	return o.WorkflowType
}

// GetWorkflowTypeOk returns a tuple with the WorkflowType field value
// and a boolean to check if the value has been set.
func (o *AuditWorkflow) GetWorkflowTypeOk() (*WorkflowTypeA27Enum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowType, true
}

// SetWorkflowType sets field value
func (o *AuditWorkflow) SetWorkflowType(v WorkflowTypeA27Enum) {
	o.WorkflowType = v
}

// GetAuditType returns the AuditType field value
func (o *AuditWorkflow) GetAuditType() AuditTypeEnum {
	if o == nil {
		var ret AuditTypeEnum
		return ret
	}

	return o.AuditType
}

// GetAuditTypeOk returns a tuple with the AuditType field value
// and a boolean to check if the value has been set.
func (o *AuditWorkflow) GetAuditTypeOk() (*AuditTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditType, true
}

// SetAuditType sets field value
func (o *AuditWorkflow) SetAuditType(v AuditTypeEnum) {
	o.AuditType = v
}

func (o AuditWorkflow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditWorkflow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["engineer"] = o.Engineer
	toSerialize["workflow_id"] = o.WorkflowId
	toSerialize["audit_remark"] = o.AuditRemark
	toSerialize["workflow_type"] = o.WorkflowType
	toSerialize["audit_type"] = o.AuditType
	return toSerialize, nil
}

func (o *AuditWorkflow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"engineer",
		"workflow_id",
		"audit_remark",
		"workflow_type",
		"audit_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditWorkflow := _AuditWorkflow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuditWorkflow)

	if err != nil {
		return err
	}

	*o = AuditWorkflow(varAuditWorkflow)

	return err
}

type NullableAuditWorkflow struct {
	value *AuditWorkflow
	isSet bool
}

func (v NullableAuditWorkflow) Get() *AuditWorkflow {
	return v.value
}

func (v *NullableAuditWorkflow) Set(val *AuditWorkflow) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditWorkflow) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditWorkflow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditWorkflow(val *AuditWorkflow) *NullableAuditWorkflow {
	return &NullableAuditWorkflow{value: val, isSet: true}
}

func (v NullableAuditWorkflow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditWorkflow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


