/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// WorkflowLogWorkflowTypeEnum * `1` - 1 * `2` - 2 * `3` - 3
type WorkflowLogWorkflowTypeEnum int32

// List of WorkflowLogWorkflowTypeEnum
const (
	WORKFLOWLOGWORKFLOWTYPEENUM__1 WorkflowLogWorkflowTypeEnum = 1
	WORKFLOWLOGWORKFLOWTYPEENUM__2 WorkflowLogWorkflowTypeEnum = 2
	WORKFLOWLOGWORKFLOWTYPEENUM__3 WorkflowLogWorkflowTypeEnum = 3
)

// All allowed values of WorkflowLogWorkflowTypeEnum enum
var AllowedWorkflowLogWorkflowTypeEnumEnumValues = []WorkflowLogWorkflowTypeEnum{
	1,
	2,
	3,
}

func (v *WorkflowLogWorkflowTypeEnum) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WorkflowLogWorkflowTypeEnum(value)
	for _, existing := range AllowedWorkflowLogWorkflowTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WorkflowLogWorkflowTypeEnum", value)
}

// NewWorkflowLogWorkflowTypeEnumFromValue returns a pointer to a valid WorkflowLogWorkflowTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWorkflowLogWorkflowTypeEnumFromValue(v int32) (*WorkflowLogWorkflowTypeEnum, error) {
	ev := WorkflowLogWorkflowTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WorkflowLogWorkflowTypeEnum: valid values are %v", v, AllowedWorkflowLogWorkflowTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WorkflowLogWorkflowTypeEnum) IsValid() bool {
	for _, existing := range AllowedWorkflowLogWorkflowTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WorkflowLogWorkflowTypeEnum value
func (v WorkflowLogWorkflowTypeEnum) Ptr() *WorkflowLogWorkflowTypeEnum {
	return &v
}

type NullableWorkflowLogWorkflowTypeEnum struct {
	value *WorkflowLogWorkflowTypeEnum
	isSet bool
}

func (v NullableWorkflowLogWorkflowTypeEnum) Get() *WorkflowLogWorkflowTypeEnum {
	return v.value
}

func (v *NullableWorkflowLogWorkflowTypeEnum) Set(val *WorkflowLogWorkflowTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowLogWorkflowTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowLogWorkflowTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowLogWorkflowTypeEnum(val *WorkflowLogWorkflowTypeEnum) *NullableWorkflowLogWorkflowTypeEnum {
	return &NullableWorkflowLogWorkflowTypeEnum{value: val, isSet: true}
}

func (v NullableWorkflowLogWorkflowTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowLogWorkflowTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

