/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowAudit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowAudit{}

// WorkflowAudit struct for WorkflowAudit
type WorkflowAudit struct {
	Engineer string `json:"engineer"`
}

type _WorkflowAudit WorkflowAudit

// NewWorkflowAudit instantiates a new WorkflowAudit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowAudit(engineer string) *WorkflowAudit {
	this := WorkflowAudit{}
	this.Engineer = engineer
	return &this
}

// NewWorkflowAuditWithDefaults instantiates a new WorkflowAudit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowAuditWithDefaults() *WorkflowAudit {
	this := WorkflowAudit{}
	return &this
}

// GetEngineer returns the Engineer field value
func (o *WorkflowAudit) GetEngineer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Engineer
}

// GetEngineerOk returns a tuple with the Engineer field value
// and a boolean to check if the value has been set.
func (o *WorkflowAudit) GetEngineerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engineer, true
}

// SetEngineer sets field value
func (o *WorkflowAudit) SetEngineer(v string) {
	o.Engineer = v
}

func (o WorkflowAudit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowAudit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["engineer"] = o.Engineer
	return toSerialize, nil
}

func (o *WorkflowAudit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"engineer",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowAudit := _WorkflowAudit{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowAudit)

	if err != nil {
		return err
	}

	*o = WorkflowAudit(varWorkflowAudit)

	return err
}

type NullableWorkflowAudit struct {
	value *WorkflowAudit
	isSet bool
}

func (v NullableWorkflowAudit) Get() *WorkflowAudit {
	return v.value
}

func (v *NullableWorkflowAudit) Set(val *WorkflowAudit) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowAudit) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowAudit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowAudit(val *WorkflowAudit) *NullableWorkflowAudit {
	return &NullableWorkflowAudit{value: val, isSet: true}
}

func (v NullableWorkflowAudit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowAudit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


