/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TwoFASave type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TwoFASave{}

// TwoFASave struct for TwoFASave
type TwoFASave struct {
	Engineer string `json:"engineer"`
	Key *string `json:"key,omitempty"`
	Phone *string `json:"phone,omitempty"`
	AuthType TwoFASaveAuthTypeEnum `json:"auth_type"`
}

type _TwoFASave TwoFASave

// NewTwoFASave instantiates a new TwoFASave object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTwoFASave(engineer string, authType TwoFASaveAuthTypeEnum) *TwoFASave {
	this := TwoFASave{}
	this.Engineer = engineer
	this.AuthType = authType
	return &this
}

// NewTwoFASaveWithDefaults instantiates a new TwoFASave object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTwoFASaveWithDefaults() *TwoFASave {
	this := TwoFASave{}
	return &this
}

// GetEngineer returns the Engineer field value
func (o *TwoFASave) GetEngineer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Engineer
}

// GetEngineerOk returns a tuple with the Engineer field value
// and a boolean to check if the value has been set.
func (o *TwoFASave) GetEngineerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engineer, true
}

// SetEngineer sets field value
func (o *TwoFASave) SetEngineer(v string) {
	o.Engineer = v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *TwoFASave) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFASave) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *TwoFASave) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *TwoFASave) SetKey(v string) {
	o.Key = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *TwoFASave) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFASave) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *TwoFASave) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *TwoFASave) SetPhone(v string) {
	o.Phone = &v
}

// GetAuthType returns the AuthType field value
func (o *TwoFASave) GetAuthType() TwoFASaveAuthTypeEnum {
	if o == nil {
		var ret TwoFASaveAuthTypeEnum
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *TwoFASave) GetAuthTypeOk() (*TwoFASaveAuthTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *TwoFASave) SetAuthType(v TwoFASaveAuthTypeEnum) {
	o.AuthType = v
}

func (o TwoFASave) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TwoFASave) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["engineer"] = o.Engineer
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	toSerialize["auth_type"] = o.AuthType
	return toSerialize, nil
}

func (o *TwoFASave) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"engineer",
		"auth_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTwoFASave := _TwoFASave{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTwoFASave)

	if err != nil {
		return err
	}

	*o = TwoFASave(varTwoFASave)

	return err
}

type NullableTwoFASave struct {
	value *TwoFASave
	isSet bool
}

func (v NullableTwoFASave) Get() *TwoFASave {
	return v.value
}

func (v *NullableTwoFASave) Set(val *TwoFASave) {
	v.value = val
	v.isSet = true
}

func (v NullableTwoFASave) IsSet() bool {
	return v.isSet
}

func (v *NullableTwoFASave) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwoFASave(val *TwoFASave) *NullableTwoFASave {
	return &NullableTwoFASave{value: val, isSet: true}
}

func (v NullableTwoFASave) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwoFASave) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


