/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the User type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &User{}

// User struct for User
type User struct {
	Id int32 `json:"id"`
	Password string `json:"password"`
	LastLogin NullableTime `json:"last_login,omitempty"`
	// 指明该用户缺省拥有所有权限。
	IsSuperuser *bool `json:"is_superuser,omitempty"`
	// 必填；长度为150个字符或以下；只能包含字母、数字、特殊字符“@”、“.”、“-”和“_”。
	Username string `json:"username" validate:"regexp=^[\\\\w.@+-]+$"`
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	Email *string `json:"email,omitempty"`
	// 指明用户是否可以登录到这个管理站点。
	IsStaff *bool `json:"is_staff,omitempty"`
	// 指明用户是否被认为是活跃的。以反选代替删除帐号。
	IsActive *bool `json:"is_active,omitempty"`
	DateJoined *time.Time `json:"date_joined,omitempty"`
	Display string `json:"display"`
	DingUserId *string `json:"ding_user_id,omitempty"`
	WxUserId *string `json:"wx_user_id,omitempty"`
	FeishuOpenId *string `json:"feishu_open_id,omitempty"`
	FailedLoginCount *int32 `json:"failed_login_count,omitempty"`
	LastLoginFailedAt NullableTime `json:"last_login_failed_at,omitempty"`
	// 该用户归属的组。一个用户将得到其归属的组的所有权限。
	Groups []int32 `json:"groups,omitempty"`
	// 这个用户的特定权限。
	UserPermissions []int32 `json:"user_permissions,omitempty"`
	ResourceGroup []int32 `json:"resource_group,omitempty"`
}

type _User User

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser(id int32, password string, username string, display string) *User {
	this := User{}
	this.Id = id
	this.Password = password
	this.Username = username
	this.Display = display
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetId returns the Id field value
func (o *User) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *User) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *User) SetId(v int32) {
	o.Id = v
}

// GetPassword returns the Password field value
func (o *User) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *User) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *User) SetPassword(v string) {
	o.Password = v
}

// GetLastLogin returns the LastLogin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetLastLogin() time.Time {
	if o == nil || IsNil(o.LastLogin.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastLogin.Get()
}

// GetLastLoginOk returns a tuple with the LastLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetLastLoginOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLogin.Get(), o.LastLogin.IsSet()
}

// HasLastLogin returns a boolean if a field has been set.
func (o *User) HasLastLogin() bool {
	if o != nil && o.LastLogin.IsSet() {
		return true
	}

	return false
}

// SetLastLogin gets a reference to the given NullableTime and assigns it to the LastLogin field.
func (o *User) SetLastLogin(v time.Time) {
	o.LastLogin.Set(&v)
}
// SetLastLoginNil sets the value for LastLogin to be an explicit nil
func (o *User) SetLastLoginNil() {
	o.LastLogin.Set(nil)
}

// UnsetLastLogin ensures that no value is present for LastLogin, not even an explicit nil
func (o *User) UnsetLastLogin() {
	o.LastLogin.Unset()
}

// GetIsSuperuser returns the IsSuperuser field value if set, zero value otherwise.
func (o *User) GetIsSuperuser() bool {
	if o == nil || IsNil(o.IsSuperuser) {
		var ret bool
		return ret
	}
	return *o.IsSuperuser
}

// GetIsSuperuserOk returns a tuple with the IsSuperuser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIsSuperuserOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSuperuser) {
		return nil, false
	}
	return o.IsSuperuser, true
}

// HasIsSuperuser returns a boolean if a field has been set.
func (o *User) HasIsSuperuser() bool {
	if o != nil && !IsNil(o.IsSuperuser) {
		return true
	}

	return false
}

// SetIsSuperuser gets a reference to the given bool and assigns it to the IsSuperuser field.
func (o *User) SetIsSuperuser(v bool) {
	o.IsSuperuser = &v
}

// GetUsername returns the Username field value
func (o *User) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *User) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *User) SetUsername(v string) {
	o.Username = v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *User) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *User) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *User) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *User) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *User) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *User) SetLastName(v string) {
	o.LastName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *User) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *User) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *User) SetEmail(v string) {
	o.Email = &v
}

// GetIsStaff returns the IsStaff field value if set, zero value otherwise.
func (o *User) GetIsStaff() bool {
	if o == nil || IsNil(o.IsStaff) {
		var ret bool
		return ret
	}
	return *o.IsStaff
}

// GetIsStaffOk returns a tuple with the IsStaff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIsStaffOk() (*bool, bool) {
	if o == nil || IsNil(o.IsStaff) {
		return nil, false
	}
	return o.IsStaff, true
}

// HasIsStaff returns a boolean if a field has been set.
func (o *User) HasIsStaff() bool {
	if o != nil && !IsNil(o.IsStaff) {
		return true
	}

	return false
}

// SetIsStaff gets a reference to the given bool and assigns it to the IsStaff field.
func (o *User) SetIsStaff(v bool) {
	o.IsStaff = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *User) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *User) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *User) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetDateJoined returns the DateJoined field value if set, zero value otherwise.
func (o *User) GetDateJoined() time.Time {
	if o == nil || IsNil(o.DateJoined) {
		var ret time.Time
		return ret
	}
	return *o.DateJoined
}

// GetDateJoinedOk returns a tuple with the DateJoined field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDateJoinedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateJoined) {
		return nil, false
	}
	return o.DateJoined, true
}

// HasDateJoined returns a boolean if a field has been set.
func (o *User) HasDateJoined() bool {
	if o != nil && !IsNil(o.DateJoined) {
		return true
	}

	return false
}

// SetDateJoined gets a reference to the given time.Time and assigns it to the DateJoined field.
func (o *User) SetDateJoined(v time.Time) {
	o.DateJoined = &v
}

// GetDisplay returns the Display field value
func (o *User) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *User) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *User) SetDisplay(v string) {
	o.Display = v
}

// GetDingUserId returns the DingUserId field value if set, zero value otherwise.
func (o *User) GetDingUserId() string {
	if o == nil || IsNil(o.DingUserId) {
		var ret string
		return ret
	}
	return *o.DingUserId
}

// GetDingUserIdOk returns a tuple with the DingUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDingUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.DingUserId) {
		return nil, false
	}
	return o.DingUserId, true
}

// HasDingUserId returns a boolean if a field has been set.
func (o *User) HasDingUserId() bool {
	if o != nil && !IsNil(o.DingUserId) {
		return true
	}

	return false
}

// SetDingUserId gets a reference to the given string and assigns it to the DingUserId field.
func (o *User) SetDingUserId(v string) {
	o.DingUserId = &v
}

// GetWxUserId returns the WxUserId field value if set, zero value otherwise.
func (o *User) GetWxUserId() string {
	if o == nil || IsNil(o.WxUserId) {
		var ret string
		return ret
	}
	return *o.WxUserId
}

// GetWxUserIdOk returns a tuple with the WxUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetWxUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.WxUserId) {
		return nil, false
	}
	return o.WxUserId, true
}

// HasWxUserId returns a boolean if a field has been set.
func (o *User) HasWxUserId() bool {
	if o != nil && !IsNil(o.WxUserId) {
		return true
	}

	return false
}

// SetWxUserId gets a reference to the given string and assigns it to the WxUserId field.
func (o *User) SetWxUserId(v string) {
	o.WxUserId = &v
}

// GetFeishuOpenId returns the FeishuOpenId field value if set, zero value otherwise.
func (o *User) GetFeishuOpenId() string {
	if o == nil || IsNil(o.FeishuOpenId) {
		var ret string
		return ret
	}
	return *o.FeishuOpenId
}

// GetFeishuOpenIdOk returns a tuple with the FeishuOpenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetFeishuOpenIdOk() (*string, bool) {
	if o == nil || IsNil(o.FeishuOpenId) {
		return nil, false
	}
	return o.FeishuOpenId, true
}

// HasFeishuOpenId returns a boolean if a field has been set.
func (o *User) HasFeishuOpenId() bool {
	if o != nil && !IsNil(o.FeishuOpenId) {
		return true
	}

	return false
}

// SetFeishuOpenId gets a reference to the given string and assigns it to the FeishuOpenId field.
func (o *User) SetFeishuOpenId(v string) {
	o.FeishuOpenId = &v
}

// GetFailedLoginCount returns the FailedLoginCount field value if set, zero value otherwise.
func (o *User) GetFailedLoginCount() int32 {
	if o == nil || IsNil(o.FailedLoginCount) {
		var ret int32
		return ret
	}
	return *o.FailedLoginCount
}

// GetFailedLoginCountOk returns a tuple with the FailedLoginCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetFailedLoginCountOk() (*int32, bool) {
	if o == nil || IsNil(o.FailedLoginCount) {
		return nil, false
	}
	return o.FailedLoginCount, true
}

// HasFailedLoginCount returns a boolean if a field has been set.
func (o *User) HasFailedLoginCount() bool {
	if o != nil && !IsNil(o.FailedLoginCount) {
		return true
	}

	return false
}

// SetFailedLoginCount gets a reference to the given int32 and assigns it to the FailedLoginCount field.
func (o *User) SetFailedLoginCount(v int32) {
	o.FailedLoginCount = &v
}

// GetLastLoginFailedAt returns the LastLoginFailedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetLastLoginFailedAt() time.Time {
	if o == nil || IsNil(o.LastLoginFailedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastLoginFailedAt.Get()
}

// GetLastLoginFailedAtOk returns a tuple with the LastLoginFailedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetLastLoginFailedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLoginFailedAt.Get(), o.LastLoginFailedAt.IsSet()
}

// HasLastLoginFailedAt returns a boolean if a field has been set.
func (o *User) HasLastLoginFailedAt() bool {
	if o != nil && o.LastLoginFailedAt.IsSet() {
		return true
	}

	return false
}

// SetLastLoginFailedAt gets a reference to the given NullableTime and assigns it to the LastLoginFailedAt field.
func (o *User) SetLastLoginFailedAt(v time.Time) {
	o.LastLoginFailedAt.Set(&v)
}
// SetLastLoginFailedAtNil sets the value for LastLoginFailedAt to be an explicit nil
func (o *User) SetLastLoginFailedAtNil() {
	o.LastLoginFailedAt.Set(nil)
}

// UnsetLastLoginFailedAt ensures that no value is present for LastLoginFailedAt, not even an explicit nil
func (o *User) UnsetLastLoginFailedAt() {
	o.LastLoginFailedAt.Unset()
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *User) GetGroups() []int32 {
	if o == nil || IsNil(o.Groups) {
		var ret []int32
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetGroupsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *User) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []int32 and assigns it to the Groups field.
func (o *User) SetGroups(v []int32) {
	o.Groups = v
}

// GetUserPermissions returns the UserPermissions field value if set, zero value otherwise.
func (o *User) GetUserPermissions() []int32 {
	if o == nil || IsNil(o.UserPermissions) {
		var ret []int32
		return ret
	}
	return o.UserPermissions
}

// GetUserPermissionsOk returns a tuple with the UserPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUserPermissionsOk() ([]int32, bool) {
	if o == nil || IsNil(o.UserPermissions) {
		return nil, false
	}
	return o.UserPermissions, true
}

// HasUserPermissions returns a boolean if a field has been set.
func (o *User) HasUserPermissions() bool {
	if o != nil && !IsNil(o.UserPermissions) {
		return true
	}

	return false
}

// SetUserPermissions gets a reference to the given []int32 and assigns it to the UserPermissions field.
func (o *User) SetUserPermissions(v []int32) {
	o.UserPermissions = v
}

// GetResourceGroup returns the ResourceGroup field value if set, zero value otherwise.
func (o *User) GetResourceGroup() []int32 {
	if o == nil || IsNil(o.ResourceGroup) {
		var ret []int32
		return ret
	}
	return o.ResourceGroup
}

// GetResourceGroupOk returns a tuple with the ResourceGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetResourceGroupOk() ([]int32, bool) {
	if o == nil || IsNil(o.ResourceGroup) {
		return nil, false
	}
	return o.ResourceGroup, true
}

// HasResourceGroup returns a boolean if a field has been set.
func (o *User) HasResourceGroup() bool {
	if o != nil && !IsNil(o.ResourceGroup) {
		return true
	}

	return false
}

// SetResourceGroup gets a reference to the given []int32 and assigns it to the ResourceGroup field.
func (o *User) SetResourceGroup(v []int32) {
	o.ResourceGroup = v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o User) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["password"] = o.Password
	if o.LastLogin.IsSet() {
		toSerialize["last_login"] = o.LastLogin.Get()
	}
	if !IsNil(o.IsSuperuser) {
		toSerialize["is_superuser"] = o.IsSuperuser
	}
	toSerialize["username"] = o.Username
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.IsStaff) {
		toSerialize["is_staff"] = o.IsStaff
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.DateJoined) {
		toSerialize["date_joined"] = o.DateJoined
	}
	toSerialize["display"] = o.Display
	if !IsNil(o.DingUserId) {
		toSerialize["ding_user_id"] = o.DingUserId
	}
	if !IsNil(o.WxUserId) {
		toSerialize["wx_user_id"] = o.WxUserId
	}
	if !IsNil(o.FeishuOpenId) {
		toSerialize["feishu_open_id"] = o.FeishuOpenId
	}
	if !IsNil(o.FailedLoginCount) {
		toSerialize["failed_login_count"] = o.FailedLoginCount
	}
	if o.LastLoginFailedAt.IsSet() {
		toSerialize["last_login_failed_at"] = o.LastLoginFailedAt.Get()
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	if !IsNil(o.UserPermissions) {
		toSerialize["user_permissions"] = o.UserPermissions
	}
	if !IsNil(o.ResourceGroup) {
		toSerialize["resource_group"] = o.ResourceGroup
	}
	return toSerialize, nil
}

func (o *User) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"password",
		"username",
		"display",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUser := _User{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUser)

	if err != nil {
		return err
	}

	*o = User(varUser)

	return err
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


