/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowContent{}

// WorkflowContent struct for WorkflowContent
type WorkflowContent struct {
	Id int32 `json:"id"`
	WorkflowId int32 `json:"workflow_id"`
	Workflow Workflow `json:"workflow"`
	SqlContent string `json:"sql_content"`
	ReviewContent string `json:"review_content"`
	ExecuteResult string `json:"execute_result"`
}

type _WorkflowContent WorkflowContent

// NewWorkflowContent instantiates a new WorkflowContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowContent(id int32, workflowId int32, workflow Workflow, sqlContent string, reviewContent string, executeResult string) *WorkflowContent {
	this := WorkflowContent{}
	this.Id = id
	this.WorkflowId = workflowId
	this.Workflow = workflow
	this.SqlContent = sqlContent
	this.ReviewContent = reviewContent
	this.ExecuteResult = executeResult
	return &this
}

// NewWorkflowContentWithDefaults instantiates a new WorkflowContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowContentWithDefaults() *WorkflowContent {
	this := WorkflowContent{}
	return &this
}

// GetId returns the Id field value
func (o *WorkflowContent) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkflowContent) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkflowContent) SetId(v int32) {
	o.Id = v
}

// GetWorkflowId returns the WorkflowId field value
func (o *WorkflowContent) GetWorkflowId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
func (o *WorkflowContent) GetWorkflowIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowId, true
}

// SetWorkflowId sets field value
func (o *WorkflowContent) SetWorkflowId(v int32) {
	o.WorkflowId = v
}

// GetWorkflow returns the Workflow field value
func (o *WorkflowContent) GetWorkflow() Workflow {
	if o == nil {
		var ret Workflow
		return ret
	}

	return o.Workflow
}

// GetWorkflowOk returns a tuple with the Workflow field value
// and a boolean to check if the value has been set.
func (o *WorkflowContent) GetWorkflowOk() (*Workflow, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Workflow, true
}

// SetWorkflow sets field value
func (o *WorkflowContent) SetWorkflow(v Workflow) {
	o.Workflow = v
}

// GetSqlContent returns the SqlContent field value
func (o *WorkflowContent) GetSqlContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SqlContent
}

// GetSqlContentOk returns a tuple with the SqlContent field value
// and a boolean to check if the value has been set.
func (o *WorkflowContent) GetSqlContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SqlContent, true
}

// SetSqlContent sets field value
func (o *WorkflowContent) SetSqlContent(v string) {
	o.SqlContent = v
}

// GetReviewContent returns the ReviewContent field value
func (o *WorkflowContent) GetReviewContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReviewContent
}

// GetReviewContentOk returns a tuple with the ReviewContent field value
// and a boolean to check if the value has been set.
func (o *WorkflowContent) GetReviewContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReviewContent, true
}

// SetReviewContent sets field value
func (o *WorkflowContent) SetReviewContent(v string) {
	o.ReviewContent = v
}

// GetExecuteResult returns the ExecuteResult field value
func (o *WorkflowContent) GetExecuteResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecuteResult
}

// GetExecuteResultOk returns a tuple with the ExecuteResult field value
// and a boolean to check if the value has been set.
func (o *WorkflowContent) GetExecuteResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecuteResult, true
}

// SetExecuteResult sets field value
func (o *WorkflowContent) SetExecuteResult(v string) {
	o.ExecuteResult = v
}

func (o WorkflowContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["workflow_id"] = o.WorkflowId
	toSerialize["workflow"] = o.Workflow
	toSerialize["sql_content"] = o.SqlContent
	toSerialize["review_content"] = o.ReviewContent
	toSerialize["execute_result"] = o.ExecuteResult
	return toSerialize, nil
}

func (o *WorkflowContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"workflow_id",
		"workflow",
		"sql_content",
		"review_content",
		"execute_result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowContent := _WorkflowContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowContent)

	if err != nil {
		return err
	}

	*o = WorkflowContent(varWorkflowContent)

	return err
}

type NullableWorkflowContent struct {
	value *WorkflowContent
	isSet bool
}

func (v NullableWorkflowContent) Get() *WorkflowContent {
	return v.value
}

func (v *NullableWorkflowContent) Set(val *WorkflowContent) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowContent) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowContent(val *WorkflowContent) *NullableWorkflowContent {
	return &NullableWorkflowContent{value: val, isSet: true}
}

func (v NullableWorkflowContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


