/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// DbTypeEnum * `mysql` - MySQL * `mssql` - MsSQL * `redis` - Redis * `pgsql` - PgSQL * `oracle` - Oracle * `mongo` - Mongo * `phoenix` - Phoenix * `odps` - ODPS * `clickhouse` - ClickHouse * `goinception` - goInception * `cassandra` - Cassandra * `doris` - Doris * `elasticsearch` - Elasticsearch * `opensearch` - OpenSearch * `memcached` - Memcached * `tdengine` - TDengine
type DbTypeEnum string

// List of DbTypeEnum
const (
	DBTYPEENUM_MYSQL DbTypeEnum = "mysql"
	DBTYPEENUM_MSSQL DbTypeEnum = "mssql"
	DBTYPEENUM_REDIS DbTypeEnum = "redis"
	DBTYPEENUM_PGSQL DbTypeEnum = "pgsql"
	DBTYPEENUM_ORACLE DbTypeEnum = "oracle"
	DBTYPEENUM_MONGO DbTypeEnum = "mongo"
	DBTYPEENUM_PHOENIX DbTypeEnum = "phoenix"
	DBTYPEENUM_ODPS DbTypeEnum = "odps"
	DBTYPEENUM_CLICKHOUSE DbTypeEnum = "clickhouse"
	DBTYPEENUM_GOINCEPTION DbTypeEnum = "goinception"
	DBTYPEENUM_CASSANDRA DbTypeEnum = "cassandra"
	DBTYPEENUM_DORIS DbTypeEnum = "doris"
	DBTYPEENUM_ELASTICSEARCH DbTypeEnum = "elasticsearch"
	DBTYPEENUM_OPENSEARCH DbTypeEnum = "opensearch"
	DBTYPEENUM_MEMCACHED DbTypeEnum = "memcached"
	DBTYPEENUM_TDENGINE DbTypeEnum = "tdengine"
)

// All allowed values of DbTypeEnum enum
var AllowedDbTypeEnumEnumValues = []DbTypeEnum{
	"mysql",
	"mssql",
	"redis",
	"pgsql",
	"oracle",
	"mongo",
	"phoenix",
	"odps",
	"clickhouse",
	"goinception",
	"cassandra",
	"doris",
	"elasticsearch",
	"opensearch",
	"memcached",
	"tdengine",
}

func (v *DbTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DbTypeEnum(value)
	for _, existing := range AllowedDbTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DbTypeEnum", value)
}

// NewDbTypeEnumFromValue returns a pointer to a valid DbTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDbTypeEnumFromValue(v string) (*DbTypeEnum, error) {
	ev := DbTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DbTypeEnum: valid values are %v", v, AllowedDbTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DbTypeEnum) IsValid() bool {
	for _, existing := range AllowedDbTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DbTypeEnum value
func (v DbTypeEnum) Ptr() *DbTypeEnum {
	return &v
}

type NullableDbTypeEnum struct {
	value *DbTypeEnum
	isSet bool
}

func (v NullableDbTypeEnum) Get() *DbTypeEnum {
	return v.value
}

func (v *NullableDbTypeEnum) Set(val *DbTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableDbTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableDbTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbTypeEnum(val *DbTypeEnum) *NullableDbTypeEnum {
	return &NullableDbTypeEnum{value: val, isSet: true}
}

func (v NullableDbTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

