/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TwoFA type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TwoFA{}

// TwoFA struct for TwoFA
type TwoFA struct {
	Engineer string `json:"engineer"`
	Enable EnableEnum `json:"enable"`
	Phone *string `json:"phone,omitempty"`
	AuthType TwoFAAuthTypeEnum `json:"auth_type"`
}

type _TwoFA TwoFA

// NewTwoFA instantiates a new TwoFA object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTwoFA(engineer string, enable EnableEnum, authType TwoFAAuthTypeEnum) *TwoFA {
	this := TwoFA{}
	this.Engineer = engineer
	this.Enable = enable
	this.AuthType = authType
	return &this
}

// NewTwoFAWithDefaults instantiates a new TwoFA object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTwoFAWithDefaults() *TwoFA {
	this := TwoFA{}
	return &this
}

// GetEngineer returns the Engineer field value
func (o *TwoFA) GetEngineer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Engineer
}

// GetEngineerOk returns a tuple with the Engineer field value
// and a boolean to check if the value has been set.
func (o *TwoFA) GetEngineerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engineer, true
}

// SetEngineer sets field value
func (o *TwoFA) SetEngineer(v string) {
	o.Engineer = v
}

// GetEnable returns the Enable field value
func (o *TwoFA) GetEnable() EnableEnum {
	if o == nil {
		var ret EnableEnum
		return ret
	}

	return o.Enable
}

// GetEnableOk returns a tuple with the Enable field value
// and a boolean to check if the value has been set.
func (o *TwoFA) GetEnableOk() (*EnableEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enable, true
}

// SetEnable sets field value
func (o *TwoFA) SetEnable(v EnableEnum) {
	o.Enable = v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *TwoFA) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFA) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *TwoFA) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *TwoFA) SetPhone(v string) {
	o.Phone = &v
}

// GetAuthType returns the AuthType field value
func (o *TwoFA) GetAuthType() TwoFAAuthTypeEnum {
	if o == nil {
		var ret TwoFAAuthTypeEnum
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *TwoFA) GetAuthTypeOk() (*TwoFAAuthTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *TwoFA) SetAuthType(v TwoFAAuthTypeEnum) {
	o.AuthType = v
}

func (o TwoFA) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TwoFA) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["engineer"] = o.Engineer
	toSerialize["enable"] = o.Enable
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	toSerialize["auth_type"] = o.AuthType
	return toSerialize, nil
}

func (o *TwoFA) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"engineer",
		"enable",
		"auth_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTwoFA := _TwoFA{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTwoFA)

	if err != nil {
		return err
	}

	*o = TwoFA(varTwoFA)

	return err
}

type NullableTwoFA struct {
	value *TwoFA
	isSet bool
}

func (v NullableTwoFA) Get() *TwoFA {
	return v.value
}

func (v *NullableTwoFA) Set(val *TwoFA) {
	v.value = val
	v.isSet = true
}

func (v NullableTwoFA) IsSet() bool {
	return v.isSet
}

func (v *NullableTwoFA) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwoFA(val *TwoFA) *NullableTwoFA {
	return &NullableTwoFA{value: val, isSet: true}
}

func (v NullableTwoFA) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwoFA) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


