/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExecuteWorkflow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecuteWorkflow{}

// ExecuteWorkflow struct for ExecuteWorkflow
type ExecuteWorkflow struct {
	Engineer *string `json:"engineer,omitempty"`
	WorkflowId int32 `json:"workflow_id"`
	WorkflowType ExecuteWorkflowWorkflowTypeEnum `json:"workflow_type"`
	Mode *ExecuteWorkflowModeEnum `json:"mode,omitempty"`
}

type _ExecuteWorkflow ExecuteWorkflow

// NewExecuteWorkflow instantiates a new ExecuteWorkflow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecuteWorkflow(workflowId int32, workflowType ExecuteWorkflowWorkflowTypeEnum) *ExecuteWorkflow {
	this := ExecuteWorkflow{}
	this.WorkflowId = workflowId
	this.WorkflowType = workflowType
	return &this
}

// NewExecuteWorkflowWithDefaults instantiates a new ExecuteWorkflow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecuteWorkflowWithDefaults() *ExecuteWorkflow {
	this := ExecuteWorkflow{}
	return &this
}

// GetEngineer returns the Engineer field value if set, zero value otherwise.
func (o *ExecuteWorkflow) GetEngineer() string {
	if o == nil || IsNil(o.Engineer) {
		var ret string
		return ret
	}
	return *o.Engineer
}

// GetEngineerOk returns a tuple with the Engineer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecuteWorkflow) GetEngineerOk() (*string, bool) {
	if o == nil || IsNil(o.Engineer) {
		return nil, false
	}
	return o.Engineer, true
}

// HasEngineer returns a boolean if a field has been set.
func (o *ExecuteWorkflow) HasEngineer() bool {
	if o != nil && !IsNil(o.Engineer) {
		return true
	}

	return false
}

// SetEngineer gets a reference to the given string and assigns it to the Engineer field.
func (o *ExecuteWorkflow) SetEngineer(v string) {
	o.Engineer = &v
}

// GetWorkflowId returns the WorkflowId field value
func (o *ExecuteWorkflow) GetWorkflowId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
func (o *ExecuteWorkflow) GetWorkflowIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowId, true
}

// SetWorkflowId sets field value
func (o *ExecuteWorkflow) SetWorkflowId(v int32) {
	o.WorkflowId = v
}

// GetWorkflowType returns the WorkflowType field value
func (o *ExecuteWorkflow) GetWorkflowType() ExecuteWorkflowWorkflowTypeEnum {
	if o == nil {
		var ret ExecuteWorkflowWorkflowTypeEnum
		return ret
	}

	return o.WorkflowType
}

// GetWorkflowTypeOk returns a tuple with the WorkflowType field value
// and a boolean to check if the value has been set.
func (o *ExecuteWorkflow) GetWorkflowTypeOk() (*ExecuteWorkflowWorkflowTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowType, true
}

// SetWorkflowType sets field value
func (o *ExecuteWorkflow) SetWorkflowType(v ExecuteWorkflowWorkflowTypeEnum) {
	o.WorkflowType = v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *ExecuteWorkflow) GetMode() ExecuteWorkflowModeEnum {
	if o == nil || IsNil(o.Mode) {
		var ret ExecuteWorkflowModeEnum
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecuteWorkflow) GetModeOk() (*ExecuteWorkflowModeEnum, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *ExecuteWorkflow) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given ExecuteWorkflowModeEnum and assigns it to the Mode field.
func (o *ExecuteWorkflow) SetMode(v ExecuteWorkflowModeEnum) {
	o.Mode = &v
}

func (o ExecuteWorkflow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecuteWorkflow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Engineer) {
		toSerialize["engineer"] = o.Engineer
	}
	toSerialize["workflow_id"] = o.WorkflowId
	toSerialize["workflow_type"] = o.WorkflowType
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	return toSerialize, nil
}

func (o *ExecuteWorkflow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workflow_id",
		"workflow_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExecuteWorkflow := _ExecuteWorkflow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExecuteWorkflow)

	if err != nil {
		return err
	}

	*o = ExecuteWorkflow(varExecuteWorkflow)

	return err
}

type NullableExecuteWorkflow struct {
	value *ExecuteWorkflow
	isSet bool
}

func (v NullableExecuteWorkflow) Get() *ExecuteWorkflow {
	return v.value
}

func (v *NullableExecuteWorkflow) Set(val *ExecuteWorkflow) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteWorkflow) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteWorkflow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteWorkflow(val *ExecuteWorkflow) *NullableExecuteWorkflow {
	return &NullableExecuteWorkflow{value: val, isSet: true}
}

func (v NullableExecuteWorkflow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteWorkflow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


