/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenObtainPair type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenObtainPair{}

// TokenObtainPair struct for TokenObtainPair
type TokenObtainPair struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Access string `json:"access"`
	Refresh string `json:"refresh"`
}

type _TokenObtainPair TokenObtainPair

// NewTokenObtainPair instantiates a new TokenObtainPair object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenObtainPair(username string, password string, access string, refresh string) *TokenObtainPair {
	this := TokenObtainPair{}
	this.Username = username
	this.Password = password
	this.Access = access
	this.Refresh = refresh
	return &this
}

// NewTokenObtainPairWithDefaults instantiates a new TokenObtainPair object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenObtainPairWithDefaults() *TokenObtainPair {
	this := TokenObtainPair{}
	return &this
}

// GetUsername returns the Username field value
func (o *TokenObtainPair) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *TokenObtainPair) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *TokenObtainPair) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *TokenObtainPair) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *TokenObtainPair) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *TokenObtainPair) SetPassword(v string) {
	o.Password = v
}

// GetAccess returns the Access field value
func (o *TokenObtainPair) GetAccess() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Access
}

// GetAccessOk returns a tuple with the Access field value
// and a boolean to check if the value has been set.
func (o *TokenObtainPair) GetAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Access, true
}

// SetAccess sets field value
func (o *TokenObtainPair) SetAccess(v string) {
	o.Access = v
}

// GetRefresh returns the Refresh field value
func (o *TokenObtainPair) GetRefresh() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Refresh
}

// GetRefreshOk returns a tuple with the Refresh field value
// and a boolean to check if the value has been set.
func (o *TokenObtainPair) GetRefreshOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Refresh, true
}

// SetRefresh sets field value
func (o *TokenObtainPair) SetRefresh(v string) {
	o.Refresh = v
}

func (o TokenObtainPair) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenObtainPair) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	toSerialize["access"] = o.Access
	toSerialize["refresh"] = o.Refresh
	return toSerialize, nil
}

func (o *TokenObtainPair) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"password",
		"access",
		"refresh",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenObtainPair := _TokenObtainPair{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenObtainPair)

	if err != nil {
		return err
	}

	*o = TokenObtainPair(varTokenObtainPair)

	return err
}

type NullableTokenObtainPair struct {
	value *TokenObtainPair
	isSet bool
}

func (v NullableTokenObtainPair) Get() *TokenObtainPair {
	return v.value
}

func (v *NullableTokenObtainPair) Set(val *TokenObtainPair) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenObtainPair) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenObtainPair) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenObtainPair(val *TokenObtainPair) *NullableTokenObtainPair {
	return &NullableTokenObtainPair{value: val, isSet: true}
}

func (v NullableTokenObtainPair) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenObtainPair) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


