/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WorkflowAuditList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowAuditList{}

// WorkflowAuditList struct for WorkflowAuditList
type WorkflowAuditList struct {
	AuditId int32 `json:"audit_id"`
	GroupName string `json:"group_name"`
	WorkflowType WorkflowTypeA27Enum `json:"workflow_type"`
	WorkflowTitle string `json:"workflow_title"`
	AuditAuthGroups string `json:"audit_auth_groups"`
	CurrentAudit string `json:"current_audit"`
	CurrentStatus CurrentStatusEnum `json:"current_status"`
	CreateUserDisplay *string `json:"create_user_display,omitempty"`
	CreateTime time.Time `json:"create_time"`
}

type _WorkflowAuditList WorkflowAuditList

// NewWorkflowAuditList instantiates a new WorkflowAuditList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowAuditList(auditId int32, groupName string, workflowType WorkflowTypeA27Enum, workflowTitle string, auditAuthGroups string, currentAudit string, currentStatus CurrentStatusEnum, createTime time.Time) *WorkflowAuditList {
	this := WorkflowAuditList{}
	this.AuditId = auditId
	this.GroupName = groupName
	this.WorkflowType = workflowType
	this.WorkflowTitle = workflowTitle
	this.AuditAuthGroups = auditAuthGroups
	this.CurrentAudit = currentAudit
	this.CurrentStatus = currentStatus
	this.CreateTime = createTime
	return &this
}

// NewWorkflowAuditListWithDefaults instantiates a new WorkflowAuditList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowAuditListWithDefaults() *WorkflowAuditList {
	this := WorkflowAuditList{}
	return &this
}

// GetAuditId returns the AuditId field value
func (o *WorkflowAuditList) GetAuditId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AuditId
}

// GetAuditIdOk returns a tuple with the AuditId field value
// and a boolean to check if the value has been set.
func (o *WorkflowAuditList) GetAuditIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditId, true
}

// SetAuditId sets field value
func (o *WorkflowAuditList) SetAuditId(v int32) {
	o.AuditId = v
}

// GetGroupName returns the GroupName field value
func (o *WorkflowAuditList) GetGroupName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value
// and a boolean to check if the value has been set.
func (o *WorkflowAuditList) GetGroupNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupName, true
}

// SetGroupName sets field value
func (o *WorkflowAuditList) SetGroupName(v string) {
	o.GroupName = v
}

// GetWorkflowType returns the WorkflowType field value
func (o *WorkflowAuditList) GetWorkflowType() WorkflowTypeA27Enum {
	if o == nil {
		var ret WorkflowTypeA27Enum
		return ret
	}

	return o.WorkflowType
}

// GetWorkflowTypeOk returns a tuple with the WorkflowType field value
// and a boolean to check if the value has been set.
func (o *WorkflowAuditList) GetWorkflowTypeOk() (*WorkflowTypeA27Enum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowType, true
}

// SetWorkflowType sets field value
func (o *WorkflowAuditList) SetWorkflowType(v WorkflowTypeA27Enum) {
	o.WorkflowType = v
}

// GetWorkflowTitle returns the WorkflowTitle field value
func (o *WorkflowAuditList) GetWorkflowTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowTitle
}

// GetWorkflowTitleOk returns a tuple with the WorkflowTitle field value
// and a boolean to check if the value has been set.
func (o *WorkflowAuditList) GetWorkflowTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowTitle, true
}

// SetWorkflowTitle sets field value
func (o *WorkflowAuditList) SetWorkflowTitle(v string) {
	o.WorkflowTitle = v
}

// GetAuditAuthGroups returns the AuditAuthGroups field value
func (o *WorkflowAuditList) GetAuditAuthGroups() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuditAuthGroups
}

// GetAuditAuthGroupsOk returns a tuple with the AuditAuthGroups field value
// and a boolean to check if the value has been set.
func (o *WorkflowAuditList) GetAuditAuthGroupsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditAuthGroups, true
}

// SetAuditAuthGroups sets field value
func (o *WorkflowAuditList) SetAuditAuthGroups(v string) {
	o.AuditAuthGroups = v
}

// GetCurrentAudit returns the CurrentAudit field value
func (o *WorkflowAuditList) GetCurrentAudit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrentAudit
}

// GetCurrentAuditOk returns a tuple with the CurrentAudit field value
// and a boolean to check if the value has been set.
func (o *WorkflowAuditList) GetCurrentAuditOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentAudit, true
}

// SetCurrentAudit sets field value
func (o *WorkflowAuditList) SetCurrentAudit(v string) {
	o.CurrentAudit = v
}

// GetCurrentStatus returns the CurrentStatus field value
func (o *WorkflowAuditList) GetCurrentStatus() CurrentStatusEnum {
	if o == nil {
		var ret CurrentStatusEnum
		return ret
	}

	return o.CurrentStatus
}

// GetCurrentStatusOk returns a tuple with the CurrentStatus field value
// and a boolean to check if the value has been set.
func (o *WorkflowAuditList) GetCurrentStatusOk() (*CurrentStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentStatus, true
}

// SetCurrentStatus sets field value
func (o *WorkflowAuditList) SetCurrentStatus(v CurrentStatusEnum) {
	o.CurrentStatus = v
}

// GetCreateUserDisplay returns the CreateUserDisplay field value if set, zero value otherwise.
func (o *WorkflowAuditList) GetCreateUserDisplay() string {
	if o == nil || IsNil(o.CreateUserDisplay) {
		var ret string
		return ret
	}
	return *o.CreateUserDisplay
}

// GetCreateUserDisplayOk returns a tuple with the CreateUserDisplay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowAuditList) GetCreateUserDisplayOk() (*string, bool) {
	if o == nil || IsNil(o.CreateUserDisplay) {
		return nil, false
	}
	return o.CreateUserDisplay, true
}

// HasCreateUserDisplay returns a boolean if a field has been set.
func (o *WorkflowAuditList) HasCreateUserDisplay() bool {
	if o != nil && !IsNil(o.CreateUserDisplay) {
		return true
	}

	return false
}

// SetCreateUserDisplay gets a reference to the given string and assigns it to the CreateUserDisplay field.
func (o *WorkflowAuditList) SetCreateUserDisplay(v string) {
	o.CreateUserDisplay = &v
}

// GetCreateTime returns the CreateTime field value
func (o *WorkflowAuditList) GetCreateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value
// and a boolean to check if the value has been set.
func (o *WorkflowAuditList) GetCreateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreateTime, true
}

// SetCreateTime sets field value
func (o *WorkflowAuditList) SetCreateTime(v time.Time) {
	o.CreateTime = v
}

func (o WorkflowAuditList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowAuditList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["audit_id"] = o.AuditId
	toSerialize["group_name"] = o.GroupName
	toSerialize["workflow_type"] = o.WorkflowType
	toSerialize["workflow_title"] = o.WorkflowTitle
	toSerialize["audit_auth_groups"] = o.AuditAuthGroups
	toSerialize["current_audit"] = o.CurrentAudit
	toSerialize["current_status"] = o.CurrentStatus
	if !IsNil(o.CreateUserDisplay) {
		toSerialize["create_user_display"] = o.CreateUserDisplay
	}
	toSerialize["create_time"] = o.CreateTime
	return toSerialize, nil
}

func (o *WorkflowAuditList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"audit_id",
		"group_name",
		"workflow_type",
		"workflow_title",
		"audit_auth_groups",
		"current_audit",
		"current_status",
		"create_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowAuditList := _WorkflowAuditList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowAuditList)

	if err != nil {
		return err
	}

	*o = WorkflowAuditList(varWorkflowAuditList)

	return err
}

type NullableWorkflowAuditList struct {
	value *WorkflowAuditList
	isSet bool
}

func (v NullableWorkflowAuditList) Get() *WorkflowAuditList {
	return v.value
}

func (v *NullableWorkflowAuditList) Set(val *WorkflowAuditList) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowAuditList) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowAuditList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowAuditList(val *WorkflowAuditList) *NullableWorkflowAuditList {
	return &NullableWorkflowAuditList{value: val, isSet: true}
}

func (v NullableWorkflowAuditList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowAuditList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


