/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Workflow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Workflow{}

// Workflow struct for Workflow
type Workflow struct {
	Id int32 `json:"id"`
	WorkflowName string `json:"workflow_name"`
	DemandUrl *string `json:"demand_url,omitempty"`
	GroupId int32 `json:"group_id"`
	GroupName string `json:"group_name"`
	DbName string `json:"db_name"`
	SyntaxType SyntaxTypeEnum `json:"syntax_type"`
	// * `False` - 否 * `True` - 是
	IsBackup *bool `json:"is_backup,omitempty"`
	Engineer *string `json:"engineer,omitempty"`
	EngineerDisplay string `json:"engineer_display"`
	Status StatusEnum `json:"status"`
	AuditAuthGroups string `json:"audit_auth_groups"`
	RunDateStart NullableTime `json:"run_date_start,omitempty"`
	RunDateEnd NullableTime `json:"run_date_end,omitempty"`
	CreateTime time.Time `json:"create_time"`
	FinishTime NullableTime `json:"finish_time"`
	IsManual IsOfflineExportEnum `json:"is_manual"`
	IsOfflineExport *IsOfflineExportEnum `json:"is_offline_export,omitempty"`
	ExportFormat NullableString `json:"export_format,omitempty"`
	FileName NullableString `json:"file_name,omitempty"`
	Instance int32 `json:"instance"`
}

type _Workflow Workflow

// NewWorkflow instantiates a new Workflow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflow(id int32, workflowName string, groupId int32, groupName string, dbName string, syntaxType SyntaxTypeEnum, engineerDisplay string, status StatusEnum, auditAuthGroups string, createTime time.Time, finishTime NullableTime, isManual IsOfflineExportEnum, instance int32) *Workflow {
	this := Workflow{}
	this.Id = id
	this.WorkflowName = workflowName
	this.GroupId = groupId
	this.GroupName = groupName
	this.DbName = dbName
	this.SyntaxType = syntaxType
	this.EngineerDisplay = engineerDisplay
	this.Status = status
	this.AuditAuthGroups = auditAuthGroups
	this.CreateTime = createTime
	this.FinishTime = finishTime
	this.IsManual = isManual
	this.Instance = instance
	return &this
}

// NewWorkflowWithDefaults instantiates a new Workflow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowWithDefaults() *Workflow {
	this := Workflow{}
	return &this
}

// GetId returns the Id field value
func (o *Workflow) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Workflow) SetId(v int32) {
	o.Id = v
}

// GetWorkflowName returns the WorkflowName field value
func (o *Workflow) GetWorkflowName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowName
}

// GetWorkflowNameOk returns a tuple with the WorkflowName field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetWorkflowNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowName, true
}

// SetWorkflowName sets field value
func (o *Workflow) SetWorkflowName(v string) {
	o.WorkflowName = v
}

// GetDemandUrl returns the DemandUrl field value if set, zero value otherwise.
func (o *Workflow) GetDemandUrl() string {
	if o == nil || IsNil(o.DemandUrl) {
		var ret string
		return ret
	}
	return *o.DemandUrl
}

// GetDemandUrlOk returns a tuple with the DemandUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Workflow) GetDemandUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DemandUrl) {
		return nil, false
	}
	return o.DemandUrl, true
}

// HasDemandUrl returns a boolean if a field has been set.
func (o *Workflow) HasDemandUrl() bool {
	if o != nil && !IsNil(o.DemandUrl) {
		return true
	}

	return false
}

// SetDemandUrl gets a reference to the given string and assigns it to the DemandUrl field.
func (o *Workflow) SetDemandUrl(v string) {
	o.DemandUrl = &v
}

// GetGroupId returns the GroupId field value
func (o *Workflow) GetGroupId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetGroupIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *Workflow) SetGroupId(v int32) {
	o.GroupId = v
}

// GetGroupName returns the GroupName field value
func (o *Workflow) GetGroupName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetGroupNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupName, true
}

// SetGroupName sets field value
func (o *Workflow) SetGroupName(v string) {
	o.GroupName = v
}

// GetDbName returns the DbName field value
func (o *Workflow) GetDbName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DbName
}

// GetDbNameOk returns a tuple with the DbName field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetDbNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DbName, true
}

// SetDbName sets field value
func (o *Workflow) SetDbName(v string) {
	o.DbName = v
}

// GetSyntaxType returns the SyntaxType field value
func (o *Workflow) GetSyntaxType() SyntaxTypeEnum {
	if o == nil {
		var ret SyntaxTypeEnum
		return ret
	}

	return o.SyntaxType
}

// GetSyntaxTypeOk returns a tuple with the SyntaxType field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetSyntaxTypeOk() (*SyntaxTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SyntaxType, true
}

// SetSyntaxType sets field value
func (o *Workflow) SetSyntaxType(v SyntaxTypeEnum) {
	o.SyntaxType = v
}

// GetIsBackup returns the IsBackup field value if set, zero value otherwise.
func (o *Workflow) GetIsBackup() bool {
	if o == nil || IsNil(o.IsBackup) {
		var ret bool
		return ret
	}
	return *o.IsBackup
}

// GetIsBackupOk returns a tuple with the IsBackup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Workflow) GetIsBackupOk() (*bool, bool) {
	if o == nil || IsNil(o.IsBackup) {
		return nil, false
	}
	return o.IsBackup, true
}

// HasIsBackup returns a boolean if a field has been set.
func (o *Workflow) HasIsBackup() bool {
	if o != nil && !IsNil(o.IsBackup) {
		return true
	}

	return false
}

// SetIsBackup gets a reference to the given bool and assigns it to the IsBackup field.
func (o *Workflow) SetIsBackup(v bool) {
	o.IsBackup = &v
}

// GetEngineer returns the Engineer field value if set, zero value otherwise.
func (o *Workflow) GetEngineer() string {
	if o == nil || IsNil(o.Engineer) {
		var ret string
		return ret
	}
	return *o.Engineer
}

// GetEngineerOk returns a tuple with the Engineer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Workflow) GetEngineerOk() (*string, bool) {
	if o == nil || IsNil(o.Engineer) {
		return nil, false
	}
	return o.Engineer, true
}

// HasEngineer returns a boolean if a field has been set.
func (o *Workflow) HasEngineer() bool {
	if o != nil && !IsNil(o.Engineer) {
		return true
	}

	return false
}

// SetEngineer gets a reference to the given string and assigns it to the Engineer field.
func (o *Workflow) SetEngineer(v string) {
	o.Engineer = &v
}

// GetEngineerDisplay returns the EngineerDisplay field value
func (o *Workflow) GetEngineerDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EngineerDisplay
}

// GetEngineerDisplayOk returns a tuple with the EngineerDisplay field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetEngineerDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EngineerDisplay, true
}

// SetEngineerDisplay sets field value
func (o *Workflow) SetEngineerDisplay(v string) {
	o.EngineerDisplay = v
}

// GetStatus returns the Status field value
func (o *Workflow) GetStatus() StatusEnum {
	if o == nil {
		var ret StatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetStatusOk() (*StatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Workflow) SetStatus(v StatusEnum) {
	o.Status = v
}

// GetAuditAuthGroups returns the AuditAuthGroups field value
func (o *Workflow) GetAuditAuthGroups() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuditAuthGroups
}

// GetAuditAuthGroupsOk returns a tuple with the AuditAuthGroups field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetAuditAuthGroupsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditAuthGroups, true
}

// SetAuditAuthGroups sets field value
func (o *Workflow) SetAuditAuthGroups(v string) {
	o.AuditAuthGroups = v
}

// GetRunDateStart returns the RunDateStart field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Workflow) GetRunDateStart() time.Time {
	if o == nil || IsNil(o.RunDateStart.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RunDateStart.Get()
}

// GetRunDateStartOk returns a tuple with the RunDateStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Workflow) GetRunDateStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunDateStart.Get(), o.RunDateStart.IsSet()
}

// HasRunDateStart returns a boolean if a field has been set.
func (o *Workflow) HasRunDateStart() bool {
	if o != nil && o.RunDateStart.IsSet() {
		return true
	}

	return false
}

// SetRunDateStart gets a reference to the given NullableTime and assigns it to the RunDateStart field.
func (o *Workflow) SetRunDateStart(v time.Time) {
	o.RunDateStart.Set(&v)
}
// SetRunDateStartNil sets the value for RunDateStart to be an explicit nil
func (o *Workflow) SetRunDateStartNil() {
	o.RunDateStart.Set(nil)
}

// UnsetRunDateStart ensures that no value is present for RunDateStart, not even an explicit nil
func (o *Workflow) UnsetRunDateStart() {
	o.RunDateStart.Unset()
}

// GetRunDateEnd returns the RunDateEnd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Workflow) GetRunDateEnd() time.Time {
	if o == nil || IsNil(o.RunDateEnd.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RunDateEnd.Get()
}

// GetRunDateEndOk returns a tuple with the RunDateEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Workflow) GetRunDateEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunDateEnd.Get(), o.RunDateEnd.IsSet()
}

// HasRunDateEnd returns a boolean if a field has been set.
func (o *Workflow) HasRunDateEnd() bool {
	if o != nil && o.RunDateEnd.IsSet() {
		return true
	}

	return false
}

// SetRunDateEnd gets a reference to the given NullableTime and assigns it to the RunDateEnd field.
func (o *Workflow) SetRunDateEnd(v time.Time) {
	o.RunDateEnd.Set(&v)
}
// SetRunDateEndNil sets the value for RunDateEnd to be an explicit nil
func (o *Workflow) SetRunDateEndNil() {
	o.RunDateEnd.Set(nil)
}

// UnsetRunDateEnd ensures that no value is present for RunDateEnd, not even an explicit nil
func (o *Workflow) UnsetRunDateEnd() {
	o.RunDateEnd.Unset()
}

// GetCreateTime returns the CreateTime field value
func (o *Workflow) GetCreateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetCreateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreateTime, true
}

// SetCreateTime sets field value
func (o *Workflow) SetCreateTime(v time.Time) {
	o.CreateTime = v
}

// GetFinishTime returns the FinishTime field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *Workflow) GetFinishTime() time.Time {
	if o == nil || o.FinishTime.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.FinishTime.Get()
}

// GetFinishTimeOk returns a tuple with the FinishTime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Workflow) GetFinishTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.FinishTime.Get(), o.FinishTime.IsSet()
}

// SetFinishTime sets field value
func (o *Workflow) SetFinishTime(v time.Time) {
	o.FinishTime.Set(&v)
}

// GetIsManual returns the IsManual field value
func (o *Workflow) GetIsManual() IsOfflineExportEnum {
	if o == nil {
		var ret IsOfflineExportEnum
		return ret
	}

	return o.IsManual
}

// GetIsManualOk returns a tuple with the IsManual field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetIsManualOk() (*IsOfflineExportEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsManual, true
}

// SetIsManual sets field value
func (o *Workflow) SetIsManual(v IsOfflineExportEnum) {
	o.IsManual = v
}

// GetIsOfflineExport returns the IsOfflineExport field value if set, zero value otherwise.
func (o *Workflow) GetIsOfflineExport() IsOfflineExportEnum {
	if o == nil || IsNil(o.IsOfflineExport) {
		var ret IsOfflineExportEnum
		return ret
	}
	return *o.IsOfflineExport
}

// GetIsOfflineExportOk returns a tuple with the IsOfflineExport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Workflow) GetIsOfflineExportOk() (*IsOfflineExportEnum, bool) {
	if o == nil || IsNil(o.IsOfflineExport) {
		return nil, false
	}
	return o.IsOfflineExport, true
}

// HasIsOfflineExport returns a boolean if a field has been set.
func (o *Workflow) HasIsOfflineExport() bool {
	if o != nil && !IsNil(o.IsOfflineExport) {
		return true
	}

	return false
}

// SetIsOfflineExport gets a reference to the given IsOfflineExportEnum and assigns it to the IsOfflineExport field.
func (o *Workflow) SetIsOfflineExport(v IsOfflineExportEnum) {
	o.IsOfflineExport = &v
}

// GetExportFormat returns the ExportFormat field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Workflow) GetExportFormat() string {
	if o == nil || IsNil(o.ExportFormat.Get()) {
		var ret string
		return ret
	}
	return *o.ExportFormat.Get()
}

// GetExportFormatOk returns a tuple with the ExportFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Workflow) GetExportFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExportFormat.Get(), o.ExportFormat.IsSet()
}

// HasExportFormat returns a boolean if a field has been set.
func (o *Workflow) HasExportFormat() bool {
	if o != nil && o.ExportFormat.IsSet() {
		return true
	}

	return false
}

// SetExportFormat gets a reference to the given NullableString and assigns it to the ExportFormat field.
func (o *Workflow) SetExportFormat(v string) {
	o.ExportFormat.Set(&v)
}
// SetExportFormatNil sets the value for ExportFormat to be an explicit nil
func (o *Workflow) SetExportFormatNil() {
	o.ExportFormat.Set(nil)
}

// UnsetExportFormat ensures that no value is present for ExportFormat, not even an explicit nil
func (o *Workflow) UnsetExportFormat() {
	o.ExportFormat.Unset()
}

// GetFileName returns the FileName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Workflow) GetFileName() string {
	if o == nil || IsNil(o.FileName.Get()) {
		var ret string
		return ret
	}
	return *o.FileName.Get()
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Workflow) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FileName.Get(), o.FileName.IsSet()
}

// HasFileName returns a boolean if a field has been set.
func (o *Workflow) HasFileName() bool {
	if o != nil && o.FileName.IsSet() {
		return true
	}

	return false
}

// SetFileName gets a reference to the given NullableString and assigns it to the FileName field.
func (o *Workflow) SetFileName(v string) {
	o.FileName.Set(&v)
}
// SetFileNameNil sets the value for FileName to be an explicit nil
func (o *Workflow) SetFileNameNil() {
	o.FileName.Set(nil)
}

// UnsetFileName ensures that no value is present for FileName, not even an explicit nil
func (o *Workflow) UnsetFileName() {
	o.FileName.Unset()
}

// GetInstance returns the Instance field value
func (o *Workflow) GetInstance() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value
// and a boolean to check if the value has been set.
func (o *Workflow) GetInstanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instance, true
}

// SetInstance sets field value
func (o *Workflow) SetInstance(v int32) {
	o.Instance = v
}

func (o Workflow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Workflow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["workflow_name"] = o.WorkflowName
	if !IsNil(o.DemandUrl) {
		toSerialize["demand_url"] = o.DemandUrl
	}
	toSerialize["group_id"] = o.GroupId
	toSerialize["group_name"] = o.GroupName
	toSerialize["db_name"] = o.DbName
	toSerialize["syntax_type"] = o.SyntaxType
	if !IsNil(o.IsBackup) {
		toSerialize["is_backup"] = o.IsBackup
	}
	if !IsNil(o.Engineer) {
		toSerialize["engineer"] = o.Engineer
	}
	toSerialize["engineer_display"] = o.EngineerDisplay
	toSerialize["status"] = o.Status
	toSerialize["audit_auth_groups"] = o.AuditAuthGroups
	if o.RunDateStart.IsSet() {
		toSerialize["run_date_start"] = o.RunDateStart.Get()
	}
	if o.RunDateEnd.IsSet() {
		toSerialize["run_date_end"] = o.RunDateEnd.Get()
	}
	toSerialize["create_time"] = o.CreateTime
	toSerialize["finish_time"] = o.FinishTime.Get()
	toSerialize["is_manual"] = o.IsManual
	if !IsNil(o.IsOfflineExport) {
		toSerialize["is_offline_export"] = o.IsOfflineExport
	}
	if o.ExportFormat.IsSet() {
		toSerialize["export_format"] = o.ExportFormat.Get()
	}
	if o.FileName.IsSet() {
		toSerialize["file_name"] = o.FileName.Get()
	}
	toSerialize["instance"] = o.Instance
	return toSerialize, nil
}

func (o *Workflow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"workflow_name",
		"group_id",
		"group_name",
		"db_name",
		"syntax_type",
		"engineer_display",
		"status",
		"audit_auth_groups",
		"create_time",
		"finish_time",
		"is_manual",
		"instance",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflow := _Workflow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflow)

	if err != nil {
		return err
	}

	*o = Workflow(varWorkflow)

	return err
}

type NullableWorkflow struct {
	value *Workflow
	isSet bool
}

func (v NullableWorkflow) Get() *Workflow {
	return v.value
}

func (v *NullableWorkflow) Set(val *Workflow) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflow) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflow(val *Workflow) *NullableWorkflow {
	return &NullableWorkflow{value: val, isSet: true}
}

func (v NullableWorkflow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


