/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TwoFAState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TwoFAState{}

// TwoFAState struct for TwoFAState
type TwoFAState struct {
	Engineer string `json:"engineer"`
}

type _TwoFAState TwoFAState

// NewTwoFAState instantiates a new TwoFAState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTwoFAState(engineer string) *TwoFAState {
	this := TwoFAState{}
	this.Engineer = engineer
	return &this
}

// NewTwoFAStateWithDefaults instantiates a new TwoFAState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTwoFAStateWithDefaults() *TwoFAState {
	this := TwoFAState{}
	return &this
}

// GetEngineer returns the Engineer field value
func (o *TwoFAState) GetEngineer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Engineer
}

// GetEngineerOk returns a tuple with the Engineer field value
// and a boolean to check if the value has been set.
func (o *TwoFAState) GetEngineerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engineer, true
}

// SetEngineer sets field value
func (o *TwoFAState) SetEngineer(v string) {
	o.Engineer = v
}

func (o TwoFAState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TwoFAState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["engineer"] = o.Engineer
	return toSerialize, nil
}

func (o *TwoFAState) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"engineer",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTwoFAState := _TwoFAState{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTwoFAState)

	if err != nil {
		return err
	}

	*o = TwoFAState(varTwoFAState)

	return err
}

type NullableTwoFAState struct {
	value *TwoFAState
	isSet bool
}

func (v NullableTwoFAState) Get() *TwoFAState {
	return v.value
}

func (v *NullableTwoFAState) Set(val *TwoFAState) {
	v.value = val
	v.isSet = true
}

func (v NullableTwoFAState) IsSet() bool {
	return v.isSet
}

func (v *NullableTwoFAState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwoFAState(val *TwoFAState) *NullableTwoFAState {
	return &NullableTwoFAState{value: val, isSet: true}
}

func (v NullableTwoFAState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwoFAState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


