/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedWorkflowContentList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedWorkflowContentList{}

// PaginatedWorkflowContentList struct for PaginatedWorkflowContentList
type PaginatedWorkflowContentList struct {
	Count int32 `json:"count"`
	Next NullableString `json:"next,omitempty"`
	Previous NullableString `json:"previous,omitempty"`
	Results []WorkflowContent `json:"results"`
}

type _PaginatedWorkflowContentList PaginatedWorkflowContentList

// NewPaginatedWorkflowContentList instantiates a new PaginatedWorkflowContentList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedWorkflowContentList(count int32, results []WorkflowContent) *PaginatedWorkflowContentList {
	this := PaginatedWorkflowContentList{}
	this.Count = count
	this.Results = results
	return &this
}

// NewPaginatedWorkflowContentListWithDefaults instantiates a new PaginatedWorkflowContentList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedWorkflowContentListWithDefaults() *PaginatedWorkflowContentList {
	this := PaginatedWorkflowContentList{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginatedWorkflowContentList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedWorkflowContentList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedWorkflowContentList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedWorkflowContentList) GetNext() string {
	if o == nil || IsNil(o.Next.Get()) {
		var ret string
		return ret
	}
	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedWorkflowContentList) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedWorkflowContentList) HasNext() bool {
	if o != nil && o.Next.IsSet() {
		return true
	}

	return false
}

// SetNext gets a reference to the given NullableString and assigns it to the Next field.
func (o *PaginatedWorkflowContentList) SetNext(v string) {
	o.Next.Set(&v)
}
// SetNextNil sets the value for Next to be an explicit nil
func (o *PaginatedWorkflowContentList) SetNextNil() {
	o.Next.Set(nil)
}

// UnsetNext ensures that no value is present for Next, not even an explicit nil
func (o *PaginatedWorkflowContentList) UnsetNext() {
	o.Next.Unset()
}

// GetPrevious returns the Previous field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedWorkflowContentList) GetPrevious() string {
	if o == nil || IsNil(o.Previous.Get()) {
		var ret string
		return ret
	}
	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedWorkflowContentList) GetPreviousOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedWorkflowContentList) HasPrevious() bool {
	if o != nil && o.Previous.IsSet() {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given NullableString and assigns it to the Previous field.
func (o *PaginatedWorkflowContentList) SetPrevious(v string) {
	o.Previous.Set(&v)
}
// SetPreviousNil sets the value for Previous to be an explicit nil
func (o *PaginatedWorkflowContentList) SetPreviousNil() {
	o.Previous.Set(nil)
}

// UnsetPrevious ensures that no value is present for Previous, not even an explicit nil
func (o *PaginatedWorkflowContentList) UnsetPrevious() {
	o.Previous.Unset()
}

// GetResults returns the Results field value
func (o *PaginatedWorkflowContentList) GetResults() []WorkflowContent {
	if o == nil {
		var ret []WorkflowContent
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedWorkflowContentList) GetResultsOk() ([]WorkflowContent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedWorkflowContentList) SetResults(v []WorkflowContent) {
	o.Results = v
}

func (o PaginatedWorkflowContentList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedWorkflowContentList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if o.Next.IsSet() {
		toSerialize["next"] = o.Next.Get()
	}
	if o.Previous.IsSet() {
		toSerialize["previous"] = o.Previous.Get()
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *PaginatedWorkflowContentList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedWorkflowContentList := _PaginatedWorkflowContentList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedWorkflowContentList)

	if err != nil {
		return err
	}

	*o = PaginatedWorkflowContentList(varPaginatedWorkflowContentList)

	return err
}

type NullablePaginatedWorkflowContentList struct {
	value *PaginatedWorkflowContentList
	isSet bool
}

func (v NullablePaginatedWorkflowContentList) Get() *PaginatedWorkflowContentList {
	return v.value
}

func (v *NullablePaginatedWorkflowContentList) Set(val *PaginatedWorkflowContentList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedWorkflowContentList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedWorkflowContentList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedWorkflowContentList(val *PaginatedWorkflowContentList) *NullablePaginatedWorkflowContentList {
	return &NullablePaginatedWorkflowContentList{value: val, isSet: true}
}

func (v NullablePaginatedWorkflowContentList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedWorkflowContentList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


