/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TableInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableInstance{}

// TableInstance struct for TableInstance
type TableInstance struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	DbType string `json:"db_type"`
	DbName string `json:"db_name"`
	TableName NullableString `json:"table_name,omitempty"`
}

type _TableInstance TableInstance

// NewTableInstance instantiates a new TableInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableInstance(id int32, name string, dbType string, dbName string) *TableInstance {
	this := TableInstance{}
	this.Id = id
	this.Name = name
	this.DbType = dbType
	this.DbName = dbName
	return &this
}

// NewTableInstanceWithDefaults instantiates a new TableInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableInstanceWithDefaults() *TableInstance {
	this := TableInstance{}
	return &this
}

// GetId returns the Id field value
func (o *TableInstance) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TableInstance) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TableInstance) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TableInstance) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TableInstance) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TableInstance) SetName(v string) {
	o.Name = v
}

// GetDbType returns the DbType field value
func (o *TableInstance) GetDbType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DbType
}

// GetDbTypeOk returns a tuple with the DbType field value
// and a boolean to check if the value has been set.
func (o *TableInstance) GetDbTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DbType, true
}

// SetDbType sets field value
func (o *TableInstance) SetDbType(v string) {
	o.DbType = v
}

// GetDbName returns the DbName field value
func (o *TableInstance) GetDbName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DbName
}

// GetDbNameOk returns a tuple with the DbName field value
// and a boolean to check if the value has been set.
func (o *TableInstance) GetDbNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DbName, true
}

// SetDbName sets field value
func (o *TableInstance) SetDbName(v string) {
	o.DbName = v
}

// GetTableName returns the TableName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TableInstance) GetTableName() string {
	if o == nil || IsNil(o.TableName.Get()) {
		var ret string
		return ret
	}
	return *o.TableName.Get()
}

// GetTableNameOk returns a tuple with the TableName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TableInstance) GetTableNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TableName.Get(), o.TableName.IsSet()
}

// HasTableName returns a boolean if a field has been set.
func (o *TableInstance) HasTableName() bool {
	if o != nil && o.TableName.IsSet() {
		return true
	}

	return false
}

// SetTableName gets a reference to the given NullableString and assigns it to the TableName field.
func (o *TableInstance) SetTableName(v string) {
	o.TableName.Set(&v)
}
// SetTableNameNil sets the value for TableName to be an explicit nil
func (o *TableInstance) SetTableNameNil() {
	o.TableName.Set(nil)
}

// UnsetTableName ensures that no value is present for TableName, not even an explicit nil
func (o *TableInstance) UnsetTableName() {
	o.TableName.Unset()
}

func (o TableInstance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["db_type"] = o.DbType
	toSerialize["db_name"] = o.DbName
	if o.TableName.IsSet() {
		toSerialize["table_name"] = o.TableName.Get()
	}
	return toSerialize, nil
}

func (o *TableInstance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"db_type",
		"db_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTableInstance := _TableInstance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTableInstance)

	if err != nil {
		return err
	}

	*o = TableInstance(varTableInstance)

	return err
}

type NullableTableInstance struct {
	value *TableInstance
	isSet bool
}

func (v NullableTableInstance) Get() *TableInstance {
	return v.value
}

func (v *NullableTableInstance) Set(val *TableInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableTableInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableTableInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableInstance(val *TableInstance) *NullableTableInstance {
	return &NullableTableInstance{value: val, isSet: true}
}

func (v NullableTableInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


