/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Tunnel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Tunnel{}

// Tunnel struct for Tunnel
type Tunnel struct {
	Id int32 `json:"id"`
	TunnelName string `json:"tunnel_name"`
	Host string `json:"host"`
	Port *int32 `json:"port,omitempty"`
	User NullableString `json:"user,omitempty"`
	Password NullableString `json:"password,omitempty"`
	Pkey NullableString `json:"pkey,omitempty"`
	PkeyPath NullableString `json:"pkey_path,omitempty"`
	PkeyPassword NullableString `json:"pkey_password,omitempty"`
	CreateTime time.Time `json:"create_time"`
	UpdateTime time.Time `json:"update_time"`
}

type _Tunnel Tunnel

// NewTunnel instantiates a new Tunnel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTunnel(id int32, tunnelName string, host string, createTime time.Time, updateTime time.Time) *Tunnel {
	this := Tunnel{}
	this.Id = id
	this.TunnelName = tunnelName
	this.Host = host
	this.CreateTime = createTime
	this.UpdateTime = updateTime
	return &this
}

// NewTunnelWithDefaults instantiates a new Tunnel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTunnelWithDefaults() *Tunnel {
	this := Tunnel{}
	return &this
}

// GetId returns the Id field value
func (o *Tunnel) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Tunnel) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Tunnel) SetId(v int32) {
	o.Id = v
}

// GetTunnelName returns the TunnelName field value
func (o *Tunnel) GetTunnelName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TunnelName
}

// GetTunnelNameOk returns a tuple with the TunnelName field value
// and a boolean to check if the value has been set.
func (o *Tunnel) GetTunnelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TunnelName, true
}

// SetTunnelName sets field value
func (o *Tunnel) SetTunnelName(v string) {
	o.TunnelName = v
}

// GetHost returns the Host field value
func (o *Tunnel) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *Tunnel) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *Tunnel) SetHost(v string) {
	o.Host = v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *Tunnel) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tunnel) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *Tunnel) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *Tunnel) SetPort(v int32) {
	o.Port = &v
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Tunnel) GetUser() string {
	if o == nil || IsNil(o.User.Get()) {
		var ret string
		return ret
	}
	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Tunnel) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// HasUser returns a boolean if a field has been set.
func (o *Tunnel) HasUser() bool {
	if o != nil && o.User.IsSet() {
		return true
	}

	return false
}

// SetUser gets a reference to the given NullableString and assigns it to the User field.
func (o *Tunnel) SetUser(v string) {
	o.User.Set(&v)
}
// SetUserNil sets the value for User to be an explicit nil
func (o *Tunnel) SetUserNil() {
	o.User.Set(nil)
}

// UnsetUser ensures that no value is present for User, not even an explicit nil
func (o *Tunnel) UnsetUser() {
	o.User.Unset()
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Tunnel) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Tunnel) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *Tunnel) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *Tunnel) SetPassword(v string) {
	o.Password.Set(&v)
}
// SetPasswordNil sets the value for Password to be an explicit nil
func (o *Tunnel) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *Tunnel) UnsetPassword() {
	o.Password.Unset()
}

// GetPkey returns the Pkey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Tunnel) GetPkey() string {
	if o == nil || IsNil(o.Pkey.Get()) {
		var ret string
		return ret
	}
	return *o.Pkey.Get()
}

// GetPkeyOk returns a tuple with the Pkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Tunnel) GetPkeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pkey.Get(), o.Pkey.IsSet()
}

// HasPkey returns a boolean if a field has been set.
func (o *Tunnel) HasPkey() bool {
	if o != nil && o.Pkey.IsSet() {
		return true
	}

	return false
}

// SetPkey gets a reference to the given NullableString and assigns it to the Pkey field.
func (o *Tunnel) SetPkey(v string) {
	o.Pkey.Set(&v)
}
// SetPkeyNil sets the value for Pkey to be an explicit nil
func (o *Tunnel) SetPkeyNil() {
	o.Pkey.Set(nil)
}

// UnsetPkey ensures that no value is present for Pkey, not even an explicit nil
func (o *Tunnel) UnsetPkey() {
	o.Pkey.Unset()
}

// GetPkeyPath returns the PkeyPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Tunnel) GetPkeyPath() string {
	if o == nil || IsNil(o.PkeyPath.Get()) {
		var ret string
		return ret
	}
	return *o.PkeyPath.Get()
}

// GetPkeyPathOk returns a tuple with the PkeyPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Tunnel) GetPkeyPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PkeyPath.Get(), o.PkeyPath.IsSet()
}

// HasPkeyPath returns a boolean if a field has been set.
func (o *Tunnel) HasPkeyPath() bool {
	if o != nil && o.PkeyPath.IsSet() {
		return true
	}

	return false
}

// SetPkeyPath gets a reference to the given NullableString and assigns it to the PkeyPath field.
func (o *Tunnel) SetPkeyPath(v string) {
	o.PkeyPath.Set(&v)
}
// SetPkeyPathNil sets the value for PkeyPath to be an explicit nil
func (o *Tunnel) SetPkeyPathNil() {
	o.PkeyPath.Set(nil)
}

// UnsetPkeyPath ensures that no value is present for PkeyPath, not even an explicit nil
func (o *Tunnel) UnsetPkeyPath() {
	o.PkeyPath.Unset()
}

// GetPkeyPassword returns the PkeyPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Tunnel) GetPkeyPassword() string {
	if o == nil || IsNil(o.PkeyPassword.Get()) {
		var ret string
		return ret
	}
	return *o.PkeyPassword.Get()
}

// GetPkeyPasswordOk returns a tuple with the PkeyPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Tunnel) GetPkeyPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PkeyPassword.Get(), o.PkeyPassword.IsSet()
}

// HasPkeyPassword returns a boolean if a field has been set.
func (o *Tunnel) HasPkeyPassword() bool {
	if o != nil && o.PkeyPassword.IsSet() {
		return true
	}

	return false
}

// SetPkeyPassword gets a reference to the given NullableString and assigns it to the PkeyPassword field.
func (o *Tunnel) SetPkeyPassword(v string) {
	o.PkeyPassword.Set(&v)
}
// SetPkeyPasswordNil sets the value for PkeyPassword to be an explicit nil
func (o *Tunnel) SetPkeyPasswordNil() {
	o.PkeyPassword.Set(nil)
}

// UnsetPkeyPassword ensures that no value is present for PkeyPassword, not even an explicit nil
func (o *Tunnel) UnsetPkeyPassword() {
	o.PkeyPassword.Unset()
}

// GetCreateTime returns the CreateTime field value
func (o *Tunnel) GetCreateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value
// and a boolean to check if the value has been set.
func (o *Tunnel) GetCreateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreateTime, true
}

// SetCreateTime sets field value
func (o *Tunnel) SetCreateTime(v time.Time) {
	o.CreateTime = v
}

// GetUpdateTime returns the UpdateTime field value
func (o *Tunnel) GetUpdateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value
// and a boolean to check if the value has been set.
func (o *Tunnel) GetUpdateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdateTime, true
}

// SetUpdateTime sets field value
func (o *Tunnel) SetUpdateTime(v time.Time) {
	o.UpdateTime = v
}

func (o Tunnel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Tunnel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tunnel_name"] = o.TunnelName
	toSerialize["host"] = o.Host
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if o.User.IsSet() {
		toSerialize["user"] = o.User.Get()
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if o.Pkey.IsSet() {
		toSerialize["pkey"] = o.Pkey.Get()
	}
	if o.PkeyPath.IsSet() {
		toSerialize["pkey_path"] = o.PkeyPath.Get()
	}
	if o.PkeyPassword.IsSet() {
		toSerialize["pkey_password"] = o.PkeyPassword.Get()
	}
	toSerialize["create_time"] = o.CreateTime
	toSerialize["update_time"] = o.UpdateTime
	return toSerialize, nil
}

func (o *Tunnel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tunnel_name",
		"host",
		"create_time",
		"update_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTunnel := _Tunnel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTunnel)

	if err != nil {
		return err
	}

	*o = Tunnel(varTunnel)

	return err
}

type NullableTunnel struct {
	value *Tunnel
	isSet bool
}

func (v NullableTunnel) Get() *Tunnel {
	return v.value
}

func (v *NullableTunnel) Set(val *Tunnel) {
	v.value = val
	v.isSet = true
}

func (v NullableTunnel) IsSet() bool {
	return v.isSet
}

func (v *NullableTunnel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTunnel(val *Tunnel) *NullableTunnel {
	return &NullableTunnel{value: val, isSet: true}
}

func (v NullableTunnel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTunnel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


