/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ExecuteWorkflowWorkflowTypeEnum * `2` - 2 * `3` - 3
type ExecuteWorkflowWorkflowTypeEnum int32

// List of ExecuteWorkflowWorkflowTypeEnum
const (
	EXECUTEWORKFLOWWORKFLOWTYPEENUM__2 ExecuteWorkflowWorkflowTypeEnum = 2
	EXECUTEWORKFLOWWORKFLOWTYPEENUM__3 ExecuteWorkflowWorkflowTypeEnum = 3
)

// All allowed values of ExecuteWorkflowWorkflowTypeEnum enum
var AllowedExecuteWorkflowWorkflowTypeEnumEnumValues = []ExecuteWorkflowWorkflowTypeEnum{
	2,
	3,
}

func (v *ExecuteWorkflowWorkflowTypeEnum) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ExecuteWorkflowWorkflowTypeEnum(value)
	for _, existing := range AllowedExecuteWorkflowWorkflowTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ExecuteWorkflowWorkflowTypeEnum", value)
}

// NewExecuteWorkflowWorkflowTypeEnumFromValue returns a pointer to a valid ExecuteWorkflowWorkflowTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewExecuteWorkflowWorkflowTypeEnumFromValue(v int32) (*ExecuteWorkflowWorkflowTypeEnum, error) {
	ev := ExecuteWorkflowWorkflowTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ExecuteWorkflowWorkflowTypeEnum: valid values are %v", v, AllowedExecuteWorkflowWorkflowTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ExecuteWorkflowWorkflowTypeEnum) IsValid() bool {
	for _, existing := range AllowedExecuteWorkflowWorkflowTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ExecuteWorkflowWorkflowTypeEnum value
func (v ExecuteWorkflowWorkflowTypeEnum) Ptr() *ExecuteWorkflowWorkflowTypeEnum {
	return &v
}

type NullableExecuteWorkflowWorkflowTypeEnum struct {
	value *ExecuteWorkflowWorkflowTypeEnum
	isSet bool
}

func (v NullableExecuteWorkflowWorkflowTypeEnum) Get() *ExecuteWorkflowWorkflowTypeEnum {
	return v.value
}

func (v *NullableExecuteWorkflowWorkflowTypeEnum) Set(val *ExecuteWorkflowWorkflowTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteWorkflowWorkflowTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteWorkflowWorkflowTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteWorkflowWorkflowTypeEnum(val *ExecuteWorkflowWorkflowTypeEnum) *NullableExecuteWorkflowWorkflowTypeEnum {
	return &NullableExecuteWorkflowWorkflowTypeEnum{value: val, isSet: true}
}

func (v NullableExecuteWorkflowWorkflowTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteWorkflowWorkflowTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

