/*
Archery API

OpenAPI 3.0

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TableInstanceLookup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableInstanceLookup{}

// TableInstanceLookup struct for TableInstanceLookup
type TableInstanceLookup struct {
	TableName string `json:"table_name"`
}

type _TableInstanceLookup TableInstanceLookup

// NewTableInstanceLookup instantiates a new TableInstanceLookup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableInstanceLookup(tableName string) *TableInstanceLookup {
	this := TableInstanceLookup{}
	this.TableName = tableName
	return &this
}

// NewTableInstanceLookupWithDefaults instantiates a new TableInstanceLookup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableInstanceLookupWithDefaults() *TableInstanceLookup {
	this := TableInstanceLookup{}
	return &this
}

// GetTableName returns the TableName field value
func (o *TableInstanceLookup) GetTableName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TableName
}

// GetTableNameOk returns a tuple with the TableName field value
// and a boolean to check if the value has been set.
func (o *TableInstanceLookup) GetTableNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TableName, true
}

// SetTableName sets field value
func (o *TableInstanceLookup) SetTableName(v string) {
	o.TableName = v
}

func (o TableInstanceLookup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableInstanceLookup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["table_name"] = o.TableName
	return toSerialize, nil
}

func (o *TableInstanceLookup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"table_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTableInstanceLookup := _TableInstanceLookup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTableInstanceLookup)

	if err != nil {
		return err
	}

	*o = TableInstanceLookup(varTableInstanceLookup)

	return err
}

type NullableTableInstanceLookup struct {
	value *TableInstanceLookup
	isSet bool
}

func (v NullableTableInstanceLookup) Get() *TableInstanceLookup {
	return v.value
}

func (v *NullableTableInstanceLookup) Set(val *TableInstanceLookup) {
	v.value = val
	v.isSet = true
}

func (v NullableTableInstanceLookup) IsSet() bool {
	return v.isSet
}

func (v *NullableTableInstanceLookup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableInstanceLookup(val *TableInstanceLookup) *NullableTableInstanceLookup {
	return &NullableTableInstanceLookup{value: val, isSet: true}
}

func (v NullableTableInstanceLookup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableInstanceLookup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


