on: [push, pull_request]
name: Test
jobs:
  test-nocache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24
        cache: false
    - run: go test ./...

    - run: go build .
      env:
        CGO_ENABLED: 0
    - uses: actions/upload-artifact@v7
      with:
        name: archery-cli-${{ matrix.os }}-1.24
        archive: false
        path: |
          archery-cli
          archery-cli.exe
        